### ISSUE TITLE
BrnBubbleText 组件 颜色 可自定义

### ISSUE THREAD

**Issue by clstech** [LianjiaTech/bruno#103]
BrnBubbleText 组件 颜色 自定义 属性 希望得到增加

**Comment by zhoujuanjuan** [comment]
感谢反馈，我们计划支持一下

**Comment by zhoujuanjuan** [comment]
已做支持，待新版本发布可用 https://github.com/LianjiaTech/bruno/pull/102/commits/97f6a1fd57463b8e575fae37300e7f9656f0070b
