### ISSUE TITLE
代码格式化问题

### ISSUE THREAD

**Issue by nasawz** [LianjiaTech/bruno#104]
请问贵团队内部采用的ide是什么？ 有对应的代码格式化配置文件吗？

有意向提交一些pr， 但是我在保存时，代码格式全部发生变化...

**Comment by hexintao** [comment]
我们 vscode 和 Android Studio 都有用的，vscode 使用的就是 dart/flutter 扩展自带的，Android Studio 使用的就是默认的配置。

![image](https://user-images.githubusercontent.com/15339683/155076173-bf298c79-5203-409d-a91a-2de27a5634c5.png)

![wecom-temp-0382f336d2c7147271972f68834e5373](https://user-images.githubusercontent.com/15339683/155077430-e6638b43-80f5-4db6-b1d8-6e047c46e4f2.png)

**Comment by nasawz** [comment]
![image](https://user-images.githubusercontent.com/372910/155276342-86b3b9a5-2668-43f6-ba35-530d7747df13.png)

如图   这里的设置是多少？

![image](https://user-images.githubusercontent.com/372910/155276435-72b08672-cfa8-4147-adaa-d104fa9751c9.png)

我这里format后遇到了自动换行的问题。

**Comment by hexintao** [comment]
配置没问题，换行的问题忽略吧，我本地也是换行的，不排除可能这一行是后来改的，没有格式化

![image](https://user-images.githubusercontent.com/15339683/155450266-ad21a0ad-b274-4972-bce9-c996b897fa3a.png)

**Comment by hexintao** [comment]
期待你的 pr 啊～～
