### ISSUE TITLE
购物车示例页面回退问题（严重）

### ISSUE THREAD

**Issue by ArrayTeng** [LianjiaTech/bruno#105]
ActionSheet 示例中我发现你们在做购物车底部跳出功能使用是 Overlay 来做的，这么做可以和Widget解耦，但是没有考虑点击返回键的情况

bug：弹出购物车列表在点击返回键，页面回退了但是购物车列表还在页面上，建议参考 WidgetsBindingObserver 的 didPopRoute 函数处理这个问题

**Comment by hexintao** [comment]
嗯嗯，这个问题开发组件的时候考虑到了，文档里边有相关说明，使用这个组件的时候需要业务方单独处理一下。
![image](https://user-images.githubusercontent.com/15339683/155062419-b265f912-86a7-4197-a6dc-bbc688c89d02.png)

感谢提醒，这个问题我也记录下，后边优化成不需要业务使用方处理的方案～

**Comment by hexintao** [comment]
https://bruno.ke.com/page/widgets/brn-selected-list-action-sheet
