### ISSUE TITLE
mac上本地启动后，在Safari上本地加载报错

### ISSUE THREAD

**Issue by 6ch** [LianjiaTech/bruno#106]
## 问题提交

标题格式：[BUG]: 

内容需包含：

**1、BUG 描述**
本地启动flutter run后，使用Safari加载服务地址后白屏报错

**2、复现步骤**
main.dart导入
` import 'package:bruno/bruno.dart';`
添加代码
```
 BrnInitializer.register(
      allThemeConfig: BrnAllThemeConfig(
          // 全局配置
          commonConfig: BrnCommonConfig(brandPrimary: Color(0xFF3072F6)),
          // dialog配置
          dialogConfig: BrnDialogConfig(radius: 12.0)));
```
启动
`flutter run -d chrome --no-sound-null-safety`
safari打开地址报错
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/25951117/155088666-a3cc6d49-9801-4b9f-b273-346faba2373a.png">
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/25951117/155088720-23961217-60da-4dec-a9a3-4d901ddff4d1.png">

**3、期望行为**

**4、运行环境**

* 运行设备 mac
* 系统 12.1
* Bruno 版本 2.2.2
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by hexintao** [comment]
这个我们这两天看下，目前暂时还没在 safari 浏览器上运行过，看着像是变量名和浏览器环境冲突了

**Comment by violinday** [comment]
@6ch 
本地 
MacOS  12.2.1
Safari 版本15.3 (17612.4.9.1.8) 
中运行 Bruno 2.2.x 分支 Demo 工程，运行正常，未出现该问题。
可否使用最新代码编译运行，如果还是有问题，辛苦附上详细的错误日志~
 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/9434515/160345944-a68db1a9-e9d8-48bd-8b13-bfabba77e922.png">

**Comment by violinday** [comment]
暂时关闭改 issue，如果后续有问题欢迎反馈~
: )
