### ISSUE TITLE
[Optimize]: 希望状态栏背景色可以定制

### ISSUE THREAD

**Issue by lemos1235** [LianjiaTech/bruno#107]
## 优化建议

内容需包含：

**1、优化描述**

系统状态栏颜色能自定义

比如：

```dart
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: BrnAppBar(
        themeData: BrnAppBarConfig(
          backgroundColor: Colors.white,
          systemUiOverlayStyle: SystemUiOverlayStyle.dark.copyWith(
            statusBarColor: Colors.transparent,
          )
        ),
        automaticallyImplyLeading: false,
        showDefaultBottom: false,
        brightness: Brightness.light,
        actions: BrnTextAction(
          "验证码登录",
          iconPressed: () {
            print('验证码登录');
          },
        ),
      ),
```
**实际上这里传入的 systemUiOverlayStyle 并没有生效。**

**2、关联组件**

BrnAppBar

**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备 android simulator
* 系统 windows 11
* Bruno 版本 null-safe

**5、附加信息**

当前效果：

![image](https://user-images.githubusercontent.com/23135552/155257412-ef41490c-0def-4678-8a68-a7cfc6c4672a.png)

期望效果：

![image](https://user-images.githubusercontent.com/23135552/155257364-5901a7fd-ecd0-434d-a36e-9ff9dc371e53.png)

**Comment by hexintao** [comment]
建议收到，我们这两天修改并验证下。如果您比较着急的话也可以直接修改，然后给我们提 pr

**Comment by violinday** [comment]
@lemos1235
经检查，BrnAppBar 可以通过两种方式设置 主题：
1. 直接通过 themeData 字段设置；
2. 通过 brightness 参数设置设置组件提供的dark、light 两种主题配置；

其中，第 2 种设置的优先级高于第 1 种，如下图所示，代码同时设置了 brightness、themeData 字段，此时由于优先级低 themeData 字段无法生效。

![image](https://user-images.githubusercontent.com/9434515/160523027-43cc3d0e-8a2a-4a65-b19b-ee607d0b0196.png)


解决方案：
构造 BrnAppBar时，不设置 brightness 字段即可~
