### ISSUE TITLE
[Optimize]: BrnTextSelectFormItem 设置 titlePaddingLg 没有生效

### ISSUE THREAD

**Issue by lemos1235** [LianjiaTech/bruno#108]
## 优化建议

内容需包含：

**1、优化描述**

代码：

```dart
  var smallFormItemConfig = BrnFormItemConfig(
    titleTextStyle: BrnTextStyle(fontSize: 14),
    hintTextStyle: BrnTextStyle(fontSize: 14),
    titlePaddingSm: EdgeInsets.zero,
    titlePaddingLg: EdgeInsets.zero,
  );

BrnTextInputFormItem(
    themeData: smallFormItemConfig,
    title: "店铺名称",
    hint: "填写店铺名称",
    onChanged: (newValue) {},
  ),
  BrnLine(),
  BrnTextSelectFormItem(
    themeData: smallFormItemConfig,
    title: "主营范围",
    hint: "",
    onTap: () {},
  ),
```
只对 BrnTextInputFormItem 生效，而对 BrnTextSelectFormItem 没有生效

**2、关联组件**

BrnTextSelectFormItem

**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备 android simulator
* 系统 windows 11
* Bruno 版本 null-safe

**5、附加信息**

当前效果：

![image](https://user-images.githubusercontent.com/23135552/155668552-f797ae8c-59d8-4148-9e05-3244fc0504cb.png)

期望效果：

全部左对齐

**Comment by zhoujuanjuan** [comment]
问题已修复https://github.com/LianjiaTech/bruno/pull/152，将跟随新版本发布，感谢反馈
