### ISSUE TITLE
关于不同设备的适配

### ISSUE THREAD

**Issue by MQYForverT** [LianjiaTech/bruno#121]
请问这套组件库是否会 自动适配不同设备的尺寸？

**Comment by violinday** [comment]
Bruno 组件库中大部分常用组件已支持主题定制能力，包括字体大小、字号、间距、颜色等。也已用在 for iPad  的线上 App 中。
可以参考[主题定制](http://bruno.ke.com/page/guide/theme) 文档。

**Comment by violinday** [comment]
暂时关闭该 issue，如果有问题欢迎反馈~ : )
