### ISSUE TITLE
BrnPopupListWindow.showPopListWindow 无法跳转至下一个界面

### ISSUE THREAD

**Issue by DreamlessRaw** [LianjiaTech/bruno#132]
`
BrnPopupListWindow.showPopListWindow(context, _key,
              data: ['評價', '退出'], onItemClick: (index, text) {
            switch (index) {
              case 0:
                Navigator.push(context,
                    MaterialPageRoute(builder: (_) => const EvaluatePage()));
                // Get.to(() => const EvaluatePage(),
                //     transition: Transition.rightToLeftWithFade);
                break;
              case 1:
                SystemNavigator.pop();
                break;
              default:
            }
          });
`
我是一名Flutter初学者,当我使用弹出的选项跳转至下一界面,我收到了这样的消息：
![image](https://user-images.githubusercontent.com/47837339/158001227-7686f656-8a96-4d62-915e-37cc547223fc.png)
最开始我以为是context的问题，但当我引入Get管理的时候错误依旧。

**Comment by DreamlessRaw** [comment]
我的当前环境:
![image](https://user-images.githubusercontent.com/47837339/158001327-96599d0c-a7b5-4266-9dac-7e8b4bb775c2.png)
![image](https://user-images.githubusercontent.com/47837339/158001342-acdce6b6-e300-4028-8bde-35cd3ec714e0.png)

**Comment by violinday** [comment]
@DreamlessRaw  此组件 onItemClick 回调后会默认进行 pop 操作，在使用时如果不清楚内部逻辑细节容易出现导致 push 失效。
暂时的解决方式是：
在 onItemclick 实现中按需 返回 true 或 false，决定是否拦截点击事件，
```
onItemClick: (index, data) {
  bool isInterceptClick = false;
  if(index == 0) {
    isInterceptClick = true;
  }

  return isInterceptClick;
}
```

此处后续考虑增加拦截控制参数，或将 pop 外置，由使用者决定是否对 popwindow 执行 pop 操作。

感谢对问题的反馈哈😄

**Comment by DreamlessRaw** [comment]
> @DreamlessRaw 此组件 onItemClick 回调后会默认进行 pop 操作，在使用时如果不清楚内部逻辑细节容易出现导致 push 失效。 暂时的解决方式是： 在 onItemclick 实现中按需 返回 true 或 false，决定是否拦截点击事件，
> 
> ```
> onItemClick: (index, data) {
>   bool isInterceptClick = false;
>   if(index == 0) {
>     isInterceptClick = true;
>   }
> 
>   return isInterceptClick;
> }
> ```
> 
> 该问题已提 pr 修复#134 感谢对问题的反馈哈😄

非常感谢，这成功解决了我的问题
