### ISSUE TITLE
如何申请加入项目维护组？

### ISSUE THREAD

**Issue by huma8848888** [LianjiaTech/bruno#136]
## 优化建议

标题格式：[Optimize]: 优化简介

内容需包含：

**1、优化描述**

**2、关联组件**

**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**
欢迎联系我：vx:A329887179

包括视频、图片等补充信息

**Comment by zhoujuanjuan** [comment]
你好，如果你有意愿一起维护，可以跟进 issue 相关信息，或者关注我们后续发布的 project 任务， 提 PR 修复和优化，项目组会及时 review 入库，并在下一次发布新版本时更新 ChangeLog，期待你的参与~
