### ISSUE TITLE
BrnCommonActionSheet中调用BrnMiddleInputDialog

### ISSUE THREAD

**Issue by MX8CLUB** [LianjiaTech/bruno#138]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

BrnCommonActionSheet中调用BrnMiddleInputDialog，BrnMiddleInputDialog打开失败，未报错误信息

**2、复现步骤**
BrnCommonActionSheet中调用BrnMiddleInputDialog
**3、期望行为**
BrnMiddleInputDialog可以正常打开
**4、运行环境**
  bruno: ^2.1.0-nullsafety.1

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by violinday** [comment]
@MX8CLUB 
`clickCallBack` 参数回调内部会有 pop 逻辑，如果不使用默认逻辑，可以使用 `onItemClickInterceptor` 拦截方法，返回 true 拦截点击事件。
详细可参考 http://bruno.ke.com/page/v2/widgets/brn-common-action-sheet#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E 文档中 `onItemClickInterceptor` 参数的说明~
