### ISSUE TITLE
希望示例代码里可以加入主题定制的详细代码

### ISSUE THREAD

**Issue by SteamPunkMao** [LianjiaTech/bruno#140]
希望示例代码里可以加入主题定制的详细代码

**Comment by zhoujuanjuan** [comment]
考虑到主题定制是辅助功能，因此 example 中没有加入 ，主题全局配置可以参照example/lib/sample/theme/config_test_utils.dart  ，详细教程请参照https://bruno.ke.com/page/guide/theme
