### ISSUE TITLE
BrnBottomTabBar为什么只有选中item文字显示？

### ISSUE THREAD

**Issue by SteamPunkMao** [LianjiaTech/bruno#141]

**Comment by SteamPunkMao** [comment]
BrnBottomTabBar为什么只有选中item文字显示？示例代码里也是同样的问题。

**Comment by violinday** [comment]
@SteamPunkMao 
这个组件确实会在特定情况下会出现字体色与背景色一致，导致无法展示的问题。
会在 2.2.x 分支 #145  中修复，请耐心等待后续版本发布，谢谢你的反馈~

**Comment by zhoujuanjuan** [comment]
该修复将跟随新版本发布，欢迎持续关注~
