### ISSUE TITLE
项目很好，希望尽快支持空安全

### ISSUE THREAD

**Issue by clf2004** [LianjiaTech/bruno#15]

**Comment by violinday** [comment]
@clf2004  
由于 Bruno 组件多，体量大，空安全的适配适配可能需要很多时间。
所以我们发起空安全迁移项目，我们仍然会全力进行空安全的适配，但是也期望更多的人能加入到我们，成为项目的一员。你可以根据 [Null Safety Guide](https://github.com/LianjiaTech/bruno/wiki/Null-Safety-Guide) 指南加入到我们~

**Comment by violinday** [comment]
#49 空安全适配进展可在这里查看
