### ISSUE TITLE
主题动态切换

### ISSUE THREAD

**Issue by Dia88888** [LianjiaTech/bruno#177]
我用一个Provider来管理Brn的主题，在notifyListeners之前我重新注册了主题，但是不可以动态切换。
![image](https://user-images.githubusercontent.com/103437996/162766906-19081d28-adb8-42b1-9bd4-a486723713ee.png)
![image](https://user-images.githubusercontent.com/103437996/162766991-38b747d9-3675-420f-b1f3-7b59aca7a39e.png)
![image](https://user-images.githubusercontent.com/103437996/162767080-3088c779-4321-4c97-a747-3467071f1903.png)
我自己定义了一套暗色和明色主题，但是好像无法应用到Brn中。即使我配置单个组件的主题也无效
这是我切换主题的代码
![image](https://user-images.githubusercontent.com/103437996/162767497-8be3e062-36ed-4fc4-9167-c052bf86d3f8.png)

**Comment by zhoujuanjuan** [comment]
收到反馈，这是内部机制问题，我们讨论优化策略，随后同步~

**Comment by zhoujuanjuan** [comment]
你好，如果要实现全局主题定制切换注册时不要传入configId ，configId 是用作同时存在多套主题定制的情况。例如这种工程结构
<img width="705" alt="image" src="https://user-images.githubusercontent.com/4566284/163548690-5267f381-1530-40ec-b43e-cb5be24b60a6.png">
并且使用组件时还需要取每个组件对应的 configId 的主题。
传入 configId ，Map中会存在两套需要自己在使用的时候取configId对应的主题
如果不传入，默认总是GLOBAL_CONFIG_ID，切换的时候会覆盖上一套，新的主题生效

**Comment by Dia88888** [comment]
> 你好，如果要 使用每个组件的 ID 主题还需要存在主题的主题，而不是配置 ID，配置是同时切换并同时注册主题的定制情况。主题会中 自己的ID会在两个配置存在的时候出现，配置ID没有正确取用，CONFIG_ID的时候总是切换GLOBAL_IG_ 的覆盖设置，新的套 <img alt="图片" width="705" src="https://user-images.githubusercontent.com/4566284/163548690-5267f381-1530-40ec-b43e-cb5be24b60a6.png">

你说的方法我试过了 我发现好像我用的BrnSelectTag这个组件的问题  因为当时我只测试了这一个组件  
![image](https://user-images.githubusercontent.com/103437996/164023177-25997cec-05f7-41ce-a20f-4dbef6dea3fa.png)
我标记的这行代码默认寻找GLOBAL_CONFIG_ID该configId 对应的主题配置，我打调试发现是可以找到我配置的主题的 但是接下来的BrnTagConfig.merge会用Brn自带的默认主题配置覆盖我自定义的主题配置

**Comment by zhoujuanjuan** [comment]
你好，这个问题确实是merge顺序错误导致，该问题已修复https://github.com/LianjiaTech/bruno/pull/194，将跟随下个版本发布，感谢反馈
