### ISSUE TITLE
[BUG] BrnTitleFormItem isRequire 参数无效

### ISSUE THREAD

**Issue by He2008** [LianjiaTech/bruno#179]
**1、BUG 描述**

`BrnTitleFormItem` 组件中 `isRequire` 参数无效

**2、复现步骤**
引入 `BrnTitleFormItem` 组件，设置 `isRequire`为 `true` 不会展示*图标

**3、期望行为**
正常展示*图标

**4、运行环境**
 bruno: 2.1.0-nullsafety.1

**5、附加信息**
没看到有展示*图标相关的代码
<img width="725" alt="image" src="https://user-images.githubusercontent.com/19567128/163121825-a80e1492-ff6e-404f-8165-253596d7ecc9.png">

**Comment by zhoujuanjuan** [comment]
你好，这个问题是组件内部未实现，我们已经安排处理https://github.com/LianjiaTech/bruno/pull/183 跟随下次发版，感谢反馈

**Comment by zhoujuanjuan** [comment]
已跟随新版本发布，如果测试还有问题欢迎再次反馈
