### ISSUE TITLE
能否尽快升级到Flutter最新版本

### ISSUE THREAD

**Issue by cgzcgb** [LianjiaTech/bruno#18]
最新版本已经是2.8了，今天想在新项目中尝试一下这些组件，发现因为版本依赖太低无法运行

**Comment by zhoujuanjuan** [comment]
> 最新版本已经是2.8了，今天想在新项目中尝试一下这些组件，发现因为版本依赖太低无法运行

Flutter 不断迭代新版本，bruno 适配会相对滞后，我们近期优先空安全迁移工作 ，感兴趣可以参照 [Null Safety Guide](https://github.com/LianjiaTech/bruno/wiki/Null-Safety-Guide) 加入我们。如果迫切需要适配 Flutter 2.8 ，建议 fork 适配，待我们更新新版本再切换，感谢关注!

**Comment by SteveCruise** [comment]
唉，Flutter兼容性不强，第三方组件不好做呀

**Comment by lzdtech** [comment]
很是期待支持2.8版本

**Comment by zhoujuanjuan** [comment]
目前正在加快空安全迁移工作中，适配新版本待 迁移完成后进行，敬请期待感兴趣也可加入我们 :point_right:  https://github.com/LianjiaTech/bruno/issues/49

**Comment by wangzhongITger** [comment]
已经2.10.2了，flutter的更新速度很快啊

**Comment by violinday** [comment]
@wangzhongITger  
近期发布了 2.1.0-nullsafty.1 PreRelease 版本，支持了空安全。
同时修复了该问题，经过初步测试，可在 2.10.0 版本正常运行。可尝试使用该版本验证功能。

Ps. 2.1.0-nullsafty.1 版本为非正式版本，由于适配了 null-safty， 且存在部分破坏性改动(breaking change)，可能引起代码编译错误。
详见：https://github.com/LianjiaTech/bruno/releases

**Comment by zhoujuanjuan** [comment]
已发布新版本适配最新的 Flutter SDK版本欢迎体验
