### ISSUE TITLE
是否支持国际化

### ISSUE THREAD

**Issue by lilong-git** [LianjiaTech/bruno#182]

**Comment by zhoujuanjuan** [comment]
目前还没有计划支持，长远看本地化的支持是很有必要的，我们也会纳入到后续规划的考虑中来，如有进展会及时同步给社区。

**Comment by momtboy** [comment]
本地化什么时候列如开发计划呢？这个功能挺需要的

**Comment by violinday** [comment]
hi @momtboy  
我们将在支持 3.0 （七月初）之后开始支持国际化。若无变化，预计会在八月份完成.

如果感兴趣也可以提交 pr 到 3.x 分支 参与 Bruno 共建，让他变得越来越好~   : )

**Comment by zhoujuanjuan** [comment]
国际化即将上线，感谢关注
