### ISSUE TITLE
[BUG] : BrnBottomTabBar 中 BrnBottomTabBarDisplayType 自定义设置无效

### ISSUE THREAD

**Issue by 5night** [LianjiaTech/bruno#186]
如构造函数：
`type = items.length <= 3
            ? BrnBottomTabBarDisplayType.fixed
            : BrnBottomTabBarDisplayType.shifting`
BrnBottomTabBarDisplayType  只和 tabbar 中 items 的个数有关，和自定义设置无关。

**Comment by violinday** [comment]
@5night 
经过对代码的 CR，这段代码本意是为了根据 `items` 设置 `BrnBottomTabBarDisplayType`，实际使用出现了与使用者预期效果不一致的情况。

后续会提 PR 优化这个问题，谢谢反馈~
