### ISSUE TITLE
有拍照控制及图片加上水印和压缩组件吗

### ISSUE THREAD

**Issue by hadoop835** [LianjiaTech/bruno#19]
有拍照控制及图片加上水印和压缩组件吗

**Comment by Nayuta403** [comment]
没有，这是一个纯 UI 组件库，不涉及功能组件

**Comment by violinday** [comment]
@hadoop835 
如 @Nayuta403  所说，这是一个纯 UI 组件库。
如有组件相关问题和建议，可随时向我们反馈~ 😄
