### ISSUE TITLE
折线图能实现点击事件绑定外部元素吗

### ISSUE THREAD

**Issue by xufengzz** [LianjiaTech/bruno#190]
## 功能需求
我想实现如下的操作。目前还没想到办法。请问应该如何在外部元素控制这个联动 
![22](https://user-images.githubusercontent.com/43258342/164727609-7349f0ea-5436-4143-9eca-860b1396dfae.png)

![221](https://user-images.githubusercontent.com/43258342/164727919-291e7335-759c-4c5d-9285-ac9e07ed12c6.png)

确实没办法了。盼回复

**Comment by violinday** [comment]
@xufengzz 想否要实现 点击月份，折线图联动的功能? 

组件未提供外部手动控制选中某个点，及获取某个点最标的能力。

可以尝试通过模拟点击事件的方式实现。不过组件也未暴露点的坐标信息，可以尝试在外部计算并缓存点的坐标信息。

```
onDateChange() { // 月份变化的回调
  GestureBinding.instance!.handlePointerEvent(PointerDownEvent( //模拟按下
    pointer: 123, // pointer id
      position: pointOffset
  ));
  GestureBinding.instance!.handlePointerEvent(PointerUpEvent( //模拟抬起
      pointer: 123, // pointer id
      position: pointOffset
  ));
}
```

**Comment by xufengzz** [comment]
> @xufengzz 想否要实现 点击月份，折线图联动的功能?
> 
> 组件未提供外部手动控制选中某个点，及获取某个点最标的能力。
> 
> 可以尝试通过模拟点击事件的方式实现。不过组件也未暴露点的坐标信息，可以尝试在外部计算并缓存点的坐标信息。
> 
> ```
> onDateChange() { // 月份变化的回调
>   GestureBinding.instance!.handlePointerEvent(PointerDownEvent( //模拟按下
>     pointer: 123, // pointer id
>       position: pointOffset
>   ));
>   GestureBinding.instance!.handlePointerEvent(PointerUpEvent( //模拟抬起
>       pointer: 123, // pointer id
>       position: pointOffset
>   ));
> }
> ```
感谢大佬回复，就是需要实现点击月份 模拟点击的事件。这个回答很好的解决了我的问题！！！

**Comment by xufengzz** [comment]
@violinday  我尝试了两个小时。不知道怎么计算折线图 原点的坐标诶。能否提供个根据图中的x y值提供个计算规则啥的。 感谢

**Comment by xufengzz** [comment]
追了一下源码 不知道这个方法是不是计算圆点坐标的。但是用了这些坐标模拟点击好像没生效。如果没问题的话 我就copy源码修改组件了~~~ 不知道啥问题。难搞
![333](https://user-images.githubusercontent.com/43258342/165114178-5ccb99b6-c567-4a59-ae33-a0557778fa41.png)
