### ISSUE TITLE
文档内容错误修改

### ISSUE THREAD

**Issue by JarynChen** [LianjiaTech/bruno#199]
<img width="2145" alt="image" src="https://user-images.githubusercontent.com/41881490/165657431-5b7de6d9-7393-4c11-b08e-210c98e02bf3.png">

应为「标签宽度」

**Comment by zhoujuanjuan** [comment]
你好，感谢反馈，问题已修复 https://github.com/LianjiaTech/bruno/pull/198，会在4月29 跟随发布新版本上线
