### ISSUE TITLE
折线图，x轴，字体倾斜角度，如何实现，柱状图有没有该功能

### ISSUE THREAD

**Issue by KN970** [LianjiaTech/bruno#211]
![image](https://user-images.githubusercontent.com/13569279/167236378-7de52d8a-ef4e-4414-b2d4-e82c0debc8fc.png)

**Comment by violinday** [comment]
hi  @KN970 
柱状图组件存在对应参数设置倾斜展示坐标刻度,如下图所示:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/9434515/175808143-6f1b6fee-3f5d-4452-830c-11c34d962f32.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/9434515/175808196-ed0a3e77-32cb-46e9-a30d-625e8e194b8a.png">

后续 Bruno 将补充完善该组件的文档，感谢反馈~  : )
