### ISSUE TITLE
BrnButtonConfig按钮主题配置参数未生效

### ISSUE THREAD

**Issue by wxuonline** [LianjiaTech/bruno#214]
按钮参数bigButtonRadius和bigButtonFontSize未生效，bigButtonHeight高度有效
使用BrnInitializer.register和themeData修改按钮圆角均无效
`
BrnBigMainButton(
    title: "登录",
    bgColor: Colours.primaryCyan,
    themeData: BrnButtonConfig(
        bigButtonRadius: Dimens.dp25,
        bigButtonHeight: Dimens.dp50,
        bigButtonFontSize: Dimens.sp18,
    ),
)
`

flutter 版本stable 2.10.5
bruno: ^2.2.0

**Comment by violinday** [comment]
@wxuonline  

BigMainButton 组件确实存在主题配置未生效的问题。组件在开始版本未支持全部主题配置的参数，后面发布版本时将优化这个问题，感谢反馈~ 😄

**Comment by violinday** [comment]
已在 #252 修复这个问题。
