### ISSUE TITLE
请问是否有对flutter 3.0支持的规划

### ISSUE THREAD

**Issue by 18505106268** [LianjiaTech/bruno#218]
目前我们项目的移动端端使用Flutter,bruno的整体UI风格也比较符合国人审美，请问是否有考虑对flutter 3.0的支持。

**Comment by threells1939** [comment]
同问

**Comment by zhoujuanjuan** [comment]
跟随 Flutter SDK 步伐是我们一直的目标和追求，目前因为 Flutter 3.0 发布不久，还需要看用户反馈和需求决定适配时间，也因近期内部资源调整会稍有延后，还请见谅~

**Comment by violinday** [comment]
#245

**Comment by violinday** [comment]
与 #245 重复了，先关闭这个 issue，统一在 #245  讨论
