### ISSUE TITLE
[Optimize]: migrate brn_theme to null safety first

### ISSUE THREAD

**Issue by laiiihz** [LianjiaTech/bruno#22]
1、优化描述
大多数组件依赖`bruno_theme`，先迁移`bruno_theme`到空安全可能更好🤣
参考 https://dart.cn/null-safety/migration-guide#migrating-by-hand

2、关联组件
library `bruno_theme`

3、具体优化建议

* 迁移`bruno_theme`到空安全
* 更新[wiki](https://github.com/LianjiaTech/bruno/wiki)

4、运行环境

branch [null-safe](https://github.com/LianjiaTech/bruno/tree/null-safe)

**Comment by Nayuta403** [comment]
Yeah PR 已经合并了~
