### ISSUE TITLE
导航栏BtnTextAction实际可点击范围较小

### ISSUE THREAD

**Issue by wxuonline** [LianjiaTech/bruno#220]
## 优化建议

标题格式：[Optimize]: 优化简介

内容需包含：

**1、优化描述**

1. BtnTextAction实际可点击范围只有中间2个字左右宽度，左右两边点击未触发iconPressed事件
![image](https://user-images.githubusercontent.com/28921455/168559531-d71f0076-c8e7-4efa-b5da-48439c6765fd.png)

2. 打印iconPressed事件有延迟和事件丢失问题，不确定是否只有我这边有这个问题还是iconPressed做了截流处理？更换系统自带AppBar后 打印点击事件非常流畅

**2、关联组件**
BrnAppBar 、BrnTextAction

**3、具体优化建议**

1. 增加BtnTextAction可点击范围
2. 优化点击事件流畅度

**4、运行环境（非必填）**

* Bruno 最新版
* Flutter 3.0

**Comment by violinday** [comment]
hi @wxuonline ,
感谢反馈~
经过本地Mi 11 pro android 12 和 web 平台鼠标点击测试：
1. 点击范围问题：未发现点击区域变窄的问题，测试后发现上下点击范围不足(如下图，**红色区域**为目前事件相应区域)，后续将会优化下变为**蓝色区域**相应事件。
<img width="397" alt="image" src="https://user-images.githubusercontent.com/9434515/175807674-2587e342-10eb-46e6-a2b4-07d043fd7ec8.png">

2. 点击延迟：内部没做拦截处理，时间响应后直接回调 iconPressed。
3. 事件丢失问题：根据目前信息来看，事件丢失是否因点击区域小导致点击事件未触发？后面继续观察。

: )

**Comment by violinday** [comment]
该问题已在 #383 中修复，并在近期版本上线，感谢反馈 ～
