### ISSUE TITLE
文档示例代码错误

### ISSUE THREAD

**Issue by JarynChen** [LianjiaTech/bruno#221]
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/41881490/168718040-0e5de2c4-12cf-4b86-a595-733144f440fe.png">

**Comment by violinday** [comment]
@JarynChen 
感谢你的反馈，我们尽快优化这个问题~

**Comment by violinday** [comment]
hi @JarynChen 
已在 #255 优化该组件文档，将随下个版本发布，感谢反馈~
