### ISSUE TITLE
BrnCheckbox首次加载，切换选中状态时右侧文字会有跳动问题

### ISSUE THREAD

**Issue by wxuonline** [LianjiaTech/bruno#222]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

BrnCheckbox首次加载时存在：
1、点击切换选中状态因为没有给icon宽高占位 右侧文字位置会有跳动
2、使用官方example示例注释未选中状态icon代码亦可复现

**5、附加信息**
example代码示例：
![image](https://user-images.githubusercontent.com/28921455/168942203-270c42fb-066a-4c8f-b74d-fc31c05f385d.png)

https://user-images.githubusercontent.com/28921455/168942368-ed1d1183-cde0-440f-9490-6f0d648f249f.mp4

版本 bruno 2.2

**Comment by wxuonline** [comment]
真难，总共就用了3个组件，3个组件都有问题，有理由怀疑代码都没有经过测试就发上来了。
暂时是不想这个组件库了，等以后优化好了再回来看看

**Comment by violinday** [comment]
hi @wxuonline, 
感谢你对 Bruno  问题的反馈。
关于文本跳动问题，经过本地测试，属于偶现问题，可能和设备、运行模式有关。已初步定位问题原因，我们会及时跟进修复，跟随后续版本解决。

关于测试，虽然我们在发版之前会组织 Bruno 开发组同学统一进行测试，但由于 Bruno 属于开源项目，人力、设备有限，部分问题可能无法发现。这也是我们开源的目的之一，通过社区反馈和共建一起让它变的越来越好。再次感谢你的反馈~

**Comment by wxuonline** [comment]
您好，文本跳动问题不属于偶现。
经过我逐帧分析：
在首次运行时，由于未缓存icon图片，所以_isSelected首次切换时一定会出现icon消失再出现的情况，导致文字跳动
本地实测 **增加iconWidth属性后 可解决次问题；**
另：
BrnCheckbox使用示例代码在android环境下 存在文本和icon对不齐问题，增加
`
strutStyle:  StrutStyle( height: 1, forceStrutHeight: true )
`
后可解决

**Comment by violinday** [comment]
@wxuonline 
抱歉，是我没有表述清楚，使用我手上的设备（mi 11 pro、iPhone 模拟器 pro max 13 iOS 15.2）测试时这个问题是偶现的，当时测试没有发现这个问题。
从你遇到的现象来看，在特定设备上应该是必现。除使用 iconWidth 之外，可否尝试使用 `gaplessPlayback` 属性解决这个问题
```
Image.asset(
      assetFilePath,
      color: color,
      gaplessPlayback: true,
      package: BrnStrings.flutterPackageName,
      scale: 3.0,
    )
```

====

文本和icon对不齐问题，我们本地看下哈。可以补充下出现问题的机型信息吗，我们尽量找对应机型测试。感谢~

**Comment by wxuonline** [comment]
调试机型：
android 10 — 小米8
android 9 — Urovo
都会出现这个问题，这个应该是android固有的字体偏下的问题

**Comment by violinday** [comment]
经过测试发现，Demo 中示例确实会有对齐问题，而且在不同机型表现不一致。
使用 `strutStyle: StrutStyle( height: 1, forceStrutHeight: true )` 在某些机型上也会出现对齐问题。

此问题应该和 Flutter 有关，字节跳动针技术团队对此问题进行过深入研究。可参考： https://my.oschina.net/u/4180867/blog/5310861

**Comment by violinday** [comment]
展示关闭 该 issue，等待官方提供解决方案。 : )
