### ISSUE TITLE
建议更新photo_view版本

### ISSUE THREAD

**Issue by SuPeiSen** [LianjiaTech/bruno#230]
## 建议更新
photo_view的旧版本有问题，会导致内存泄漏，具体可以参考这个[链接](https://github.com/bluefireteam/photo_view/issues/489)
更新到```photo_view 0.14.0```则可以解决这个错误

遇到的错误的小伙伴可以通过强制这个[photo_view](https://pub.flutter-io.cn/packages/photo_view/install)版本来避免这个错误
```yaml
dependency_overrides:
  photo_view: ^0.14.0
```

**Comment by violinday** [comment]
hi @SuPeiSen ,
感谢反馈~ 
已提交  代码更新 photo_view 版本，后续版本将会使用最新 phto_view 版本 #254
