### ISSUE TITLE
能否在Form表单中的TextInput新增功能

### ISSUE THREAD

**Issue by nieshuo** [LianjiaTech/bruno#231]
比如新增密码可见和不可见
还有在末尾新增Icon按钮可以清楚已输入的数据

**Comment by violinday** [comment]
hi @nieshuo 
Bruno 现有组件中提供了[BrnGeneralFormItem](http://bruno.ke.com/page/v2.2.0/widgets/brn-general-form-item) 基础数据录入组件，提供了灵活的参数配置。 
根据你的描述，可将自定义【密码、末尾 icon】作为 Widget 参入 `operateWidget`中展示。 : )

**Comment by fyang0728** [comment]
看不懂 BrnGeneralFormItem 这个组件怎么使用。能做为输入框使用吗？也没看到输入框怎么嵌套进去。
