### ISSUE TITLE
BrnSmallOutlineButton fontweight 修改自定义设置无效

### ISSUE THREAD

**Issue by xyhuangjia** [LianjiaTech/bruno#233]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

设置 fontweight 未常规字重并未生效。

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by violinday** [comment]
hi @xyhuangjia 
可否提供下 问题复现步骤，包括运行代码、Flutter SDK、Bruno 版本、问题机型等信息，
方便我们复现该问题。 ：）

**Comment by xyhuangjia** [comment]
> hi @xyhuangjia
> 可否提供下 问题复现步骤，包括运行代码、Flutter SDK、Bruno 版本、问题机型等信息，
> 方便我们复现该问题。 ：）

代码内部自定义设置未生效，已拉取分枝调整对应代码

**Comment by violinday** [comment]
> > hi @xyhuangjia
> > 可否提供下 问题复现步骤，包括运行代码、Flutter SDK、Bruno 版本、问题机型等信息，
> > 方便我们复现该问题。 ：）
> 
> 代码内部自定义设置未生效，已拉取分枝调整对应代码

经过查看，BrnSmallOutlineButton 确实存在 bug，已在 #256 修复，会跟随后续版本上线，感谢反馈~
