### ISSUE TITLE
BrnSelectionView，type：daterange 建议增加时分秒配置

### ISSUE THREAD

**Issue by zerael2020** [LianjiaTech/bruno#234]
## 优化建议

标题格式：[Optimize]: BrnSelectionView，type：daterange 建议增加时分秒配置

内容需包含：

**1、优化描述**
特定情况下需要查询当前是时分秒
**2、关联组件**
BrnSelectionView
**3、具体优化建议**
调整daterange组件或者增加新组件
**4、运行环境（非必填）**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by violinday** [comment]
@zerael2020  感谢你的建议，我们后续会对是否增加这个能力进行评估。

仅考虑时间选择组件，目前已有[BrnDatePicker](http://bruno.ke.com/page/v2.1.0/widgets/brn-date-picker)， 可供使用。

**Comment by violinday** [comment]
暂时关闭该 issue，如还有问题欢迎提 issue 
：）
