### ISSUE TITLE
BrnStepInputFormItem 手动输入时输入位置错误

### ISSUE THREAD

**Issue by Elenring** [LianjiaTech/bruno#235]
## 问题提交

[BUG]: BrnStepInputFormItem 手动输入时输入位置错误

内容需包含：

**1、BUG 描述**
BrnStepInputFormItem 手动输入时输入位置错误

**2、复现步骤**

- 手动输入数字，每次改变值光标位置就会变化，导致输入值位置错误
- 删除时每次值变化，都会导致无法继续删除（就像失去焦点一样，但是光标还在），除非再次点击输入框才可继续删除

**3、图片展示**
![08FE0E4A63F5DFFE2A099744F3A65761](https://user-images.githubusercontent.com/59725293/172347672-baa41a17-2036-45b2-abf2-f101977501bf.gif)

**Comment by jixiaoyong** [comment]
这个光标位置错误是[RangeLimitedTextInputFormatter.formatEditUpdate](https://github.com/LianjiaTech/bruno/blob/dfd8816db71071fd82fa2b9dba906d7799473b68/lib/src/components/form/items/general/brn_step_input_item.dart#L329)方法返回了错误的TextSelection导致的。

![image](https://user-images.githubusercontent.com/18367427/173269765-58b762c6-78a0-4d9d-9758-958a2e2cf27c.png)

如果官方没有人安排修复的话，我待会儿提个pull request，修复这个问题。

但是对于下面这种文本清空之后的光标显示不确定应该怎么处理：隐藏光标，还是加入一个空白字符占位，或者不处理？

![image](https://user-images.githubusercontent.com/18367427/173270455-a5ecec42-ce48-4d00-9427-9b24d4029c49.png)

**Comment by Elenring** [comment]
> 这个光标位置错误是[RangeLimitedTextInputFormatter.formatEditUpdate](https://github.com/LianjiaTech/bruno/blob/dfd8816db71071fd82fa2b9dba906d7799473b68/lib/src/components/form/items/general/brn_step_input_item.dart#L329)方法返回了错误的TextSelection导致的。
> 
> ![image](https://user-images.githubusercontent.com/18367427/173269765-58b762c6-78a0-4d9d-9758-958a2e2cf27c.png)
> 
> 如果官方没有人安排修复的话，我待会儿提个pull request，修复这个问题。
> 
> 但是对于下面这种文本清空之后的光标显示不确定应该怎么处理：隐藏光标，还是加入一个空白字符占位，或者不处理？
> 
> ![image](https://user-images.githubusercontent.com/18367427/173270455-a5ecec42-ce48-4d00-9427-9b24d4029c49.png)

十分感谢你的解答回复，根据你说的，问题解决了
