### ISSUE TITLE
[BUG]: BrnSimpleSelection 无法动态更新

### ISSUE THREAD

**Issue by MX8CLUB** [LianjiaTech/bruno#242]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

BrnSimpleSelection.radio 当list为动态更新加载时无法更新UI展示

**2、复现步骤**
1. 进入页面
2. 获取数据并setState
3. 下拉未刷新

**3、期望行为**
ui同步更新

**4、运行环境**

* 运行设备 android
* 系统 win10
* Bruno 版本 2.2.0
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by MX8CLUB** [comment]
找到有说异步请求的，可是感觉不太清楚，可否能够讲解一下具体实现
https://bruno.ke.com/page/v2.2.0/widgets/brn-selection-view#注意事项

**Comment by MX8CLUB** [comment]
已解决

**Comment by liuchaowei666** [comment]
您好，这个是怎么解决的
