### ISSUE TITLE
建议官方文档增加组件总览页，将图片改成可交互组件，参考ant-design文档

### ISSUE THREAD

**Issue by threells1939** [LianjiaTech/bruno#243]
#228 
之前这条提过将图片改成gif，感觉直接将组件嵌入进去可以交互更为直观，如今主流的UI库文档，如ant-design、有赞UI的文档都是这种形式

**Comment by hxywuya** [comment]
同意的不能再同意了，毕竟flutter现在也能支持打包成web了

**Comment by zhoujuanjuan** [comment]
官网已经上线 web 在线演示功能，可供查看，感谢反馈
