### ISSUE TITLE
BrnDialogManager.showSingleButtonDialog 弹窗主题无效果

### ISSUE THREAD

**Issue by LoveBabyForeve** [LianjiaTech/bruno#259]
BrnDialogManager.showSingleButtonDialog(context,
    themeData: BrnDialogConfig(
      backgroundColor: Colors.red,
        assistActionsTextStyle: BrnTextStyle(
            color: Colors.red
        ),
        titleTextStyle: BrnTextStyle(
            color: Colors.red
        )
    ),
    label: "复制",
    title: '填写示例',
    message: message,
    onTap: () {
      Clipboard.setData(ClipboardData(text: message));
      Get.back();
    });

设置主题颜色无效果

**Comment by violinday** [comment]
hi  @LoveBabyForeve ,感谢你的反馈。

经过测试发现确实存在这个 bug，我们会在 3.x 分支修复这个问题，新版本会在一周左右发出，可以持续关注~
