### ISSUE TITLE
BrnSelectTag 添加边框

### ISSUE THREAD

**Issue by xyhuangjia** [LianjiaTech/bruno#268]
## 优化建议

标题格式：[Optimize]: 优化简介

内容需包含：

**1、优化描述**
BrnSelectTag 添加边框

**2、关联组件**
BrnSelectTag 
**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by zhoujuanjuan** [comment]
您好，如果您想要带边框的标签样式，建议您使用BrnTagCustom 组件的 buildBorderTag()构造方法，感谢反馈

**Comment by xyhuangjia** [comment]
> 您好，如果您想要带边框的标签样式，建议您使用BrnTagCustom 组件的 buildBorderTag()构造方法，感谢反馈

em，我们需求是带边框的且可以单选或者多选，BrnTagCustom控件不满足要求，已fork分支做过相应的处理，依然谢谢反馈
