### ISSUE TITLE
BrnTextInputFormItem 无法异步更新默认值

### ISSUE THREAD

**Issue by xyhuangjia** [LianjiaTech/bruno#269]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

我在接口请求返回数据后希望赋值给 ```TextEditController()..text```。结果未生效，排查代码后发现
```
  @override
  void initState() {
    _controller = widget.controller ?? TextEditingController();
    super.initState();
  }
```
异步处理时无法修改 _controller 的值
**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by zhoujuanjuan** [comment]
你好，如果需要接口异步更新显示，可以初始化传入controller，并在接口返回时更新controller.text ，目前看组件是可以满足异步需求的。如还未解决问题辛苦附上使用代码供我们排查

**Comment by xyhuangjia** [comment]
> 你好，如果需要接口异步更新显示，可以初始化传入controller，并在接口返回时更新controller.text ，目前看组件是可以满足异步需求的。如还未解决问题辛苦附上使用代码供我们排查


代码如下
```
BrnTextInputFormItem(
                            controller: TextEditingController()..text = qssx,
                            isRequire: true,
                            title: "****($qsdw)",
                            hint: "请输入****",
                            onChanged: (text) {
                              qssx = text;
                            },
                            themeData: inputTFConfig,
                          ),
```

`qssx` 为接口返回参数

**Comment by xyhuangjia** [comment]
确实可以，谢谢
