### ISSUE TITLE
[TODO] 迁移至空安全

### ISSUE THREAD

**Issue by AlexV525** [LianjiaTech/bruno#27]
- Components
- Theme, Constants #28 
- Utils #30
- Example

**Comment by KennethYo** [comment]
这个事情，有 timeline 吗？ 想把 bruno 作为项目的组件库，设计已经接收，但是空安全比较 block。

**Comment by zhoujuanjuan** [comment]
> 这个事情，有 timeline 吗？ 想把 bruno 作为项目的组件库，设计已经接受，但是空安全比较 block。

感谢关注，我们预计将在1月31号左右完成空安全迁移工作，可以保持关注[项目进度](https://github.com/LianjiaTech/bruno/projects/1)，也欢迎参与到迁移[共建](https://github.com/LianjiaTech/bruno/wiki/Null-Safety-Guide)中来

**Comment by violinday** [comment]
我们近期发布了 2.1.0-nullsafty.1 PreRelease 版本，支持了空安全。
同时修复了该问题，经过初步测试，可在 2.10.0 版本正常运行。可尝试使用该版本验证功能。

Ps. 2.1.0-nullsafty.1 版本为非正式版本，由于适配了 null-safty， 且存在部分破坏性改动(breaking change)，可能引起代码编译错误。
详见：https://github.com/LianjiaTech/bruno/releases
