### ISSUE TITLE
DateRangePicker 日期选择  之前的 支 能否自定义或多语言

### ISSUE THREAD

**Issue by zhaoweiguo5505** [LianjiaTech/bruno#276]
## 功能需求

![image](https://user-images.githubusercontent.com/34048223/177899308-4ce59bc2-eafe-4c93-be36-b514ae75757d.png)

**Comment by violinday** [comment]
多语言能力已在开发中，即将发版的 3.0.0 还不支持。

预计在3.0.0 之后的版本上线，若无变化预计在 7 月份发布小版本上线 。 : )

**Comment by zhoujuanjuan** [comment]
国际化即将发布，感谢关注
