### ISSUE TITLE
BrnProgressChart 设置颜色，背景色，以及动画无效

### ISSUE THREAD

**Issue by k3v1n-uncle** [LianjiaTech/bruno#280]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

BrnProgressChart 设置颜色，背景色，以及动画无效，改成其他颜色无效

**2、复现步骤**
BrnProgressChart(
                        key: UniqueKey(),
                        width: 750,
                        height: 2,
                        value: pageProgress,
                        colors: const [Colors.lightGreen, Colors.green],
                        backgroundColor: Colors.grey,
                        showAnimation: true,
                      ),

**3、期望行为**

能自定义颜色，背景色，动画貌似中途会回滚到0

**4、运行环境**

[✓] Flutter (Channel stable, 2.10.5, on macOS 11.6.6 20G624 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)

Bruno：3.0.0

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by zhoujuanjuan** [comment]
您好，backgroundColor 内部确实未使用，Animation  加载也确实有描述问题，我们安排会尽快安排优化，感谢你的反馈

**Comment by leftcoding** [comment]
已修复 https://github.com/LianjiaTech/bruno/pull/322 @zhoujuanjuan
