### ISSUE TITLE
BrnBrokenLine 同时显示多条线提示窗口

### ISSUE THREAD

**Issue by 309791679** [LianjiaTech/bruno#282]
## 问题提交

实例中并未提及 同时显示多条线提示窗口，
选择线，下方提示文字颜色改变

* 运行设备
* 小米k40
* 系统
* win10
* Bruno 版本
* 3.0.0
* Flutter Doctor 信息

**5、附加信息**
![image](https://user-images.githubusercontent.com/26238458/178942445-1f29c2a1-5136-45e8-98d5-d5002b816a9e.png)

**Comment by 309791679** [comment]
例如说，成都 选择线同时选择两个点，成都颜色同步修改

**Comment by 309791679** [comment]
@violinday 可否看看我的问题

**Comment by zhoujuanjuan** [comment]
你好，刻度上的选中高亮显示确实没有支持，抱歉给你带来不好的体验，我们会尽快安排支持

**Comment by 309791679** [comment]
> 

不单单是这个问题，第二个图，多条线处于一个纵轴时图片上显示出来的效果是，同时选中了两个纵轴座标点并且有两个提示框，这个也没有实现，我觉得这个应该在文档上告知的

**Comment by 309791679** [comment]
> 你好，刻度上的选中高亮显示确实没有支持，抱歉给你带来不好的体验，我们会尽快安排支持
不单单是这个问题，第二个图，多条线处于一个纵轴时图片上显示出来的效果是，同时选中了两个纵轴座标点并且有两个提示框，这个也没有实现，我觉得这个应该在文档上告知的

**Comment by 309791679** [comment]
> 你好，刻度上的选中高亮显示确实没有支持，抱歉给你带来不好的体验，我们会尽快安排支持

不单单是这个问题，第二个图，多条线处于一个纵轴时图片上显示出来的效果是，同时选中了两个纵轴座标点并且有两个提示框，这个也没有实现，我觉得这个应该在文档上告知的

**Comment by zhoujuanjuan** [comment]
是的，多条线弹窗也确实没有实现，近期资源比较紧张，还请耐心等待，如果您已经有实现想法也欢迎提 Pull Request

**Comment by violinday** [comment]
@309791679  组件将选中弹窗展示效果交给外部设置，第二张图的展示效果可通过自定义`BrnLineTouchData`的 `onTouch`实现。根据需要自定义，如样式、内容布局等Widget, 见 Demo 示例 

<img width="663" alt="image" src="https://user-images.githubusercontent.com/9434515/193173792-d38f0d26-aa68-40eb-918d-479e2abbdf0f.png">

不过组件文档中没有明显给出使用示例，后面补充下。

ps. 通过 BrnBrokrnLine 组件参数设置 整合多折线点 展示功能还未实现，有资源后优化，感谢反馈~

**Comment by zhoujuanjuan** [comment]
https://github.com/LianjiaTech/bruno/pull/319
