### ISSUE TITLE
BrnBottomTabBarItem 中 selectedTextStyle 和 unSelectedTextStyle 不生效

### ISSUE THREAD

**Issue by lilong-git** [LianjiaTech/bruno#285]
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/15997769/179788125-4d2b2204-ee6a-4180-a18e-0223c8576555.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/15997769/179788183-287fface-2ebc-4d1b-a180-47de2f1b3413.png">

**Comment by JunCaiLi** [comment]
hi ~ @violinday  对该issue 提交了一个PR https://github.com/LianjiaTech/bruno/pull/288
