### ISSUE TITLE
xml版本升级一下吧

### ISSUE THREAD

**Issue by git91895** [LianjiaTech/bruno#287]
Because flutter_svg >=1.1.0 depends on xml ^6.0.1 and bruno 3.0.0 depends on xml ^5.1.2, flutter_svg >=1.1.0 is incompatible with bruno 3.0.0.
And because no versions of bruno match >3.0.0 <4.0.0, flutter_svg >=1.1.0 is incompatible with bruno ^3.0.0.
So, because vrtap depends on both bruno ^3.0.0 and flutter_svg ^1.1.1+1, version solving failed.
pub get failed (1; So, because vrtap depends on both bruno ^3.0.0 and flutter_svg ^1.1.1+1, version solving failed.)

**Comment by zhoujuanjuan** [comment]
你好，目前 bruno 功能不依赖 xml 新版本，我们也会考虑在一个版本升级依赖库，暂时解决方案在所在工程 ymal 中使用 dependency_overrides  加入您需要的版本覆盖 bruno 中依赖版本

**Comment by hhstore** [comment]
> 你好，目前 bruno 功能不依赖 xml 新版本，我们也会考虑在一个版本升级依赖库，暂时解决方案在所在工程 ymal 中使用 dependency_overrides 加入您需要的版本覆盖 bruno 中依赖版本

- `flutter_svg` 使用非常高频. 
- 这么久了, 还是升一下[bruno](https://github.com/LianjiaTech/bruno) 依赖的 `xml` 版本吧? 一直冲突, 也是阻碍其他人使用本项目的. 
- 虽然 `dependency_overrides` 能解决问题. 但是, 不升级 `xml` 版本的理由是什么啊?

**Comment by hhstore** [comment]
#303

**Comment by hhstore** [comment]
#303

**Comment by zhoujuanjuan** [comment]
你好，上次反馈问题我们已经封板因此没有跟随上次发版，我们会在即将发布的版本中升级，感谢反馈

**Comment by zhoujuanjuan** [comment]
xml 版本已升级，感谢反馈
