### ISSUE TITLE
BrnLoadingDialog 文字过长 会造成页面越界

### ISSUE THREAD

**Issue by zhaoweiguo5505** [LianjiaTech/bruno#295]
![image](https://user-images.githubusercontent.com/34048223/181404820-862692ca-7119-4f3d-989d-4b66733a15e2.png)
<img width="260" alt="image" src="https://user-images.githubusercontent.com/34048223/181404840-3749447a-e6b5-43e4-a306-6c24122a4dab.png">

Bruno. 版本 2.2.0

**Comment by zhaoweiguo5505** [comment]
![image](https://user-images.githubusercontent.com/34048223/181412290-b6c2a7e0-e38d-4dbf-8e73-1ef03eb46fb4.png)
这里固定住了宽高。同时使用row。导致文字过长会出现页面错误

**Comment by zhoujuanjuan** [comment]
你好，这确实是我们设计的一个缺陷，我们内部讨论下合理方案

**Comment by zhoujuanjuan** [comment]
https://github.com/LianjiaTech/bruno/pull/298
