### ISSUE TITLE
sketch 插件代码能开源么？

### ISSUE THREAD

**Issue by xueyifei123** [LianjiaTech/bruno#296]

**Comment by zhoujuanjuan** [comment]
你好，感谢对 Bruno 的关注，目前还没有开源的打算，Sketch 插件的原理相关介绍请参阅 https://juejin.cn/post/7081218382116651045https://juejin.cn/post/7081218382116651045，如果有疑问可以在文章下发留言，团队成员会积极回复解决您的疑惑~

**Comment by violinday** [comment]
@xueyifei123 sketch 插件是基于 [Sketch Meaxure](https://github.com/qjebbs/sketch-meaxure) 开发，原理文章中其实说的很清楚了。

当然后续我们尝试申请开源，更方大家大家使用~
