### ISSUE TITLE
表单项能不能支持自定义icon?

### ISSUE THREAD

**Issue by fyang0728** [LianjiaTech/bruno#297]
请问：我想在表单项的尾部添加icon 有什么办法可以实现吗？

看了BrnGeneralFormItem这个组件半天真的不知道是干什么的。

**Comment by JunCaiLi** [comment]
Hi~ @fyang0728  BrnGeneralFormItem 有一个operateWidget 参数接收一个Widget，你可以传一个想要的icon widget

**Comment by fyang0728** [comment]
> 你好~@fyang0728 BrnGeneralFormItem 有一个操作小部件参数接收一个小部件，你可以传一个想要的图标小部件

但是它并不是一个可输入的东西控件，不知道是bug 还是什么地方的配置有问题

**Comment by zhoujuanjuan** [comment]
> BrnGeneralFormItem

你好，我们整体的UI设计上输入框后面是不再增加icon的，但是正如[JunCaiLi](https://github.com/JunCaiLi) 所说确实可以用BrnGeneralFormItem  的operateWidget ，将输入框和icon组合传入，希望可以解决你的问题

**Comment by fyang0728** [comment]
> > BrnGeneralFormItem
> 
> 你好，我们整体的UI设计上输入框后面是不再增加icon的，但是正如[JunCaiLi](https://github.com/JunCaiLi) 所说确实可以用BrnGeneralFormItem 的operateWidget ，将输入框和icon组合传入，希望可以解决你的问题

问题是BrnGeneralFormItem 不支持输入呀；

算了，我已经用你们代码重新改了一个符合我需求的版本了。
