### ISSUE TITLE
强烈建议组件和字体自适应

### ISSUE THREAD

**Issue by k3v1n-uncle** [LianjiaTech/bruno#299]
## 优化建议
强烈建议组件和字体自适应，或者使用screenutil插件，在pda小尺寸屏幕上，显示的不好，自体过大，望适配，谢谢
标题格式：[Optimize]: 优化简介

内容需包含：

**1、优化描述**

**2、关联组件**

**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by zhoujuanjuan** [comment]
你好，请将你的pad型号和UI截图贴一下~

**Comment by zasray** [comment]
> 你好，请将你的pad型号和UI截图贴一下~

是PDA 不是PAD

**Comment by leftcoding** [comment]
> > 你好，请将你的pad型号和UI截图贴一下~
> 
> 是PDA 不是PAD

我做过类似的，你可以自定义一些主题或者字体大小。让美工根据不通分辨率放大不通的字体大小。
