### ISSUE TITLE
Issue 提交注意事项

### ISSUE THREAD

**Issue by Nayuta403** [LianjiaTech/bruno#3]
Bruno 在公司内是一个时间跨度大，贡献者多的项目，虽然已经经过多条业务线累计上万次的引用。但从开源项目来看，它仍是一个蹒跚学步的婴儿，需要成长。如果你在使用过程中遇到了问题，或者有什么建议，欢迎 issue 与我们交流共建，**我们非常期待与你一起将 Bruno 做成 Flutter 生态中最有影响力的组件项目**。

为了更高效的沟通，你的行为可以参考以下指南：

## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

问题的描述，请尽量使用简短、准确的语言

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

## 功能需求

在提功能需求之前，建议先查询组件文档，考虑你需要的功能是否可以通过组件其他属性完成。如无法解决 ，issue 参考：

标题格式：[Feature]:  需求描述

内容需包含：

**1、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**2、是否有与之关联的 issue**

**3、描述你期望的解决方案**

**4、附加信息**

包括视频、图片等补充信息

## 优化建议

标题格式：[Optimize]: 优化简介

内容需包含：

**1、优化描述**

**2、关联组件**

**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by Silence-dream** [comment]
建议添加 issue template 这样方便大家,防止遗忘复制 issue 提问模板
[详情](https://docs.github.com/cn/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by zhoujuanjuan** [comment]
> 建议添加 issue template 这样方便大家,防止遗忘复制 issue 提问模板 [详情](https://docs.github.com/cn/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

good idea  @violinday
