### ISSUE TITLE
想问一下。国际版什么时候出来

### ISSUE THREAD

**Issue by zhaoweiguo5505** [LianjiaTech/bruno#304]
## 功能需求

在提功能需求之前，建议先查询组件文档，考虑你需要的功能是否可以通过组件其他属性完成。如无法解决 ，issue 参考：

标题格式：[Feature]:  需求描述

内容需包含：

**1、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**2、是否有与之关联的 issue**

**3、描述你期望的解决方案**

**4、附加信息**

包括视频、图片等补充信息

**Comment by zhoujuanjuan** [comment]
你好，原预计 8月底之前发本地化版本，PR已经在线，目前我们在做词的提取，还请期待

**Comment by hhstore** [comment]
- 多语言的支持, 可以参考这个项目的做法: 
    - https://github.com/bdlukaa/fluent_ui/pull/216/files
- 或者, 另外一种是集成 GetX, GetX 自带的`多语言模块`, 也非常简单+易用.

**Comment by zhoujuanjuan** [comment]
国际化即将发布，感谢关注
