### ISSUE TITLE
dialog 点击按钮关闭，无法关闭，Navigator.pop(context);关闭的是dialog的背景页面

### ISSUE THREAD

**Issue by gkdgo** [LianjiaTech/bruno#308]
## 问题提交

dialog无法正常关闭

内容需包含：

**1、BUG 描述**

dialog点击确定无法关闭，点击遮罩层可以正常关闭，使用Navigator.pop(context);会关闭dialog的背景页面而不是dialog本身

**2、复现步骤**

```dart

class Login extends StatefulWidget {
  const Login({Key? key}) : super(key: key);

  @override
  State<Login> createState() => _LoginState();
}


class _LoginState extends State<Login> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ElevatedButton(
          onPressed: () {
            BrnDialogManager.showSingleButtonDialog(context,
                label: "知道了", message: "辅助内容容信息", onTap: () {
                  BrnToast.show('知道了', context);
                  Navigator.of(context).pop();
                  // Navigator.pop(context);
                });
          },
          child: null,
        ),
      ),
    );
  }
}

```

**3、期望行为**
点击‘知道了’关闭dialog
**4、运行环境**

* 运行设备 mac
* 系统 macos
* Bruno 版本 3.0.0
* Flutter Doctor 信息 
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (2 available)   
**5、附加信息**

包括视频、图片等补充信息

**Comment by JunCaiLi** [comment]
在web端和ios端 没有复现

**Comment by zhoujuanjuan** [comment]
你好，根据您的描述没有复现该问题，还请提供详细信息

**Comment by laowangDemon** [comment]
我也遇到了相同的问题，当前弹窗不关闭，背景页面返回了上一页面

**Comment by laowangDemon** [comment]
不知道问题提出者大哥是如何解决的
