### ISSUE TITLE
增加BrnTagsPickerConfig外边距配置项

### ISSUE THREAD

**Issue by gkdgo** [LianjiaTech/bruno#315]
## 问题提交

标题格式：增加BrnTagsPickerConfig外边距配置项

内容需包含：

**1、BUG 描述**

当BrnMultiSelectTagsPicker的layoutStyle为 BrnMultiSelectTagsLayoutStyle.auto时，上下两排tags会贴在一起
image

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本 3.0.0
* Flutter Doctor 信息

**5、附加信息**

![image](https://user-images.githubusercontent.com/55651847/187949259-29e3f9e9-7437-476b-abf3-573eb27bbfd6.png)

**Comment by zhoujuanjuan** [comment]
你好，请贴下使用代码
