### ISSUE TITLE
当BrnMultiSelectTagsPicker的layoutStyle设置为BrnMultiSelectTagsLayoutStyle.auto时，很多异常。

### ISSUE THREAD

**Issue by gkdgo** [LianjiaTech/bruno#316]
## 问题提交

标题格式：当BrnMultiSelectTagsPicker的layoutStyle设置为BrnMultiSelectTagsLayoutStyle.auto时，很多异常。

内容需包含：

1. 选择的tag颜色异常
![image](https://user-images.githubusercontent.com/55651847/187950247-9b1f323e-1070-4114-bbe3-d68478c9199a.png)

2. 设置了只能选择一个，却可以选两个
![image](https://user-images.githubusercontent.com/55651847/187950390-d8c6138a-d669-4267-8671-3d28dabb8353.png)

3. 上下两行tag没有间隙

问题的描述，请尽量使用简短、准确的语言

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本 3.0.0
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by JunCaiLi** [comment]
@zhoujuanjuan  Hi~ Sandy 针对这个issue 提交了一个PR https://github.com/LianjiaTech/bruno/pull/320

**Comment by zhoujuanjuan** [comment]
你好 @gkdgo ，颜色和选中数量问题，感谢 @JunCaiLi J 已提交PR修复，间距问题目前没有复现，还请贴详细代码

**Comment by gkdgo** [comment]
> 你好 @gkdgo ，颜色和选中数量问题，感谢 @JunCaiLi J 提交PR修复，间距问题目前没有复现，还请贴详细代码和手机机型，感谢反馈

在iphone 13 pro上正常，在macOS12.5.1上面间距过小

**Comment by zhoujuanjuan** [comment]
你好，目前 bruno 适用于移动端设备规范，对于桌面的支持有限，还请选择性使用，组件部分属性是可以主题定制的，如需要可以参照配置或许可以满足你的需求
