### ISSUE TITLE
LoadingDialog的退出问题

### ISSUE THREAD

**Issue by kubiAye** [LianjiaTech/bruno#317]
让LoadingDialog消失的方法是调用dismiss.
但是我调用dismiss的时候,有可能我的Loadingdialog已经通过返回键从路由中移除了,这会导致路由会pop当前页面
有什么方法可以不通过路由让LoadingDialog dismiss吗

**Comment by zhoujuanjuan** [comment]
你好，这个问题我们已做优化，稍后提PR，感谢反馈

**Comment by zhoujuanjuan** [comment]
#321

**Comment by violinday** [comment]
具体方法可以参考这个提交，暂时关闭这个，如果还有问题可以重现打开或重开 issue。
 :)
