### ISSUE TITLE
BrnLoadingDialog.dismiss 优化建议

### ISSUE THREAD

**Issue by JadynChan** [LianjiaTech/bruno#324]
调用BrnLoadingDialog.dismiss的时候， 如果之前的BrnLoadingDialog已经消失了， 会关闭当前页。可否在dismiss方法加个判断，如果没有BrnLoadingDialog就不处理

**Comment by leftcoding** [comment]
这个问题已经优化了，可以参考 https://github.com/LianjiaTech/bruno/pull/321

**Comment by leftcoding** [comment]
这个问题已经优化了，可以参考 https://github.com/LianjiaTech/bruno/pull/321

**Comment by leftcoding** [comment]
这个问题已经优化了，可以参考 https://github.com/LianjiaTech/bruno/pull/321
