### ISSUE TITLE
BrnSingleSelectCityPage城市选择器组件，说明文档中的例子无法使用，CityInfo没有这个类，以及是否可以给出如何外部传值城市json对象，请更新文档。

### ISSUE THREAD

**Issue by DaYang816** [LianjiaTech/bruno#329]
BrnSingleSelectCityPage城市选择器组件，说明文档中的例子无法使用，CityInfo没有这个类，以及是否可以给出如何外部传值城市json对象，请更新文档。

**Comment by DaYang816** [comment]
初始化赋值
`List<CarsBreed> breedList = [];
List<BrnSelectCityModel> hotCityList = [];//这个必须写组件必须传值源码要求
@override
  void initState() {
    // TODO: implement initState
    super.initState();
    breedList.add(CarsBreed(
      breed_name: '加菲猫',
      letter: 'J',
      breed_id: '2',
    ));
    breedList.add(CarsBreed(
      breed_name: '橘猫',
      letter: 'J',
      breed_id: '3',
    ));
    breedList.add(CarsBreed(
      breed_name: '三花猫',
      letter: 'S',
      breed_id: '1',
    ));
  }`
重写方法
`class CarsBreed extends BrnSelectCityModel {
  String breed_name = "";
  String letter = "";
  String breed_id = "";

  CarsBreed({
    required this.breed_name,
    this.letter = "",
    this.breed_id = "",
  }) : super(name: breed_name, tagIndex: letter, cityCode: breed_id);//传入父类的对应的位置

  //要重写这个方法，后面点击回调用的
  @override
  String toString() =>
      "BreddBean {" +
      " \"breed_name\":\"" +
      breed_name +
      "\"" +
      " \"breed_id\":\"" +
      breed_id +
      "\"" +
      '}';
}`
在放入组件
`BrnSingleSelectCityPage(
        appBarTitle: '品种选择',
        hotCityList: hotCityList,
        cityList: breedList,
        onValueChanged: (value) => controller.setBreed(value));`
这样就可以自定义传的内容了

**Comment by leftcoding** [comment]
城市city json，可以参考这个 bruno/assets/json/china.json 文件，默认是读取这个文件内容。

**Comment by DaYang816** [comment]
> 城市city json，可以参考这个 bruno/assets/json/china.json 文件，默认是读取这个文件内容。

谢谢你的回复，这个我是了解的，我只是想让城市选择器变成别的选择器哈哈哈，文档毕竟没更新很久了

**Comment by leftcoding** [comment]
hotcity 网站上没有及时更新，可以参考demo例子。
List<BrnSelectCityModel> hotCityList = [];
    hotCityList.addAll([
      BrnSelectCityModel(name: "北京市"),
      BrnSelectCityModel(name: "广州市"),
      BrnSelectCityModel(name: "成都市"),
      BrnSelectCityModel(name: "深圳市"),
      BrnSelectCityModel(name: "杭州市"),
      BrnSelectCityModel(name: "武汉市"),
    ]);
    return BrnSingleSelectCityPage(
      appBarTitle: '城市单选',
      hotCityTitle: '这里是推荐城市',
      hotCityList: hotCityList,
    );

**Comment by leftcoding** [comment]
> 

你可以参考新的来写，就可以用了，后面考虑下单独抽离出来一个组件，方便大家使用

**Comment by DaYang816** [comment]
> hotcity 网站上没有及时更新，可以参考demo例子。 List hotCityList = []; hotCityList.addAll([ BrnSelectCityModel(name: "北京市"), BrnSelectCityModel(name: "广州市"), BrnSelectCityModel(name: "成都市"), BrnSelectCityModel(name: "深圳市"), BrnSelectCityModel(name: "杭州市"), BrnSelectCityModel(name: "武汉市"), ]); return BrnSingleSelectCityPage( appBarTitle: '城市单选', hotCityTitle: '这里是推荐城市', hotCityList: hotCityList, );

谢谢你的回复，我也是收到原先文档的启发，然后阅读了一下整个布局，毕竟项目里面有城市选择器，有地区，有种类，只要用一个组件就可以了，就不用找别的组件了，看文档没有说怎么去写自己的json进去 所以想补充一下解决个别需求

**Comment by DaYang816** [comment]
> > 
> 
> 你可以参考新的来写，就可以用了，后面考虑下单独抽离出来一个组件，方便大家使用

个人感觉已经很不错了，只要重写一下方法就能随便用了，不像别的要固定格式啥的，还要嵌套哈哈

**Comment by leftcoding** [comment]
> > > 
> > 
> > 
> > 你可以参考新的来写，就可以用了，后面考虑下单独抽离出来一个组件，方便大家使用
> 
> 个人感觉已经很不错了，只要重写一下方法就能随便用了，不像别的要固定格式啥的，还要嵌套哈哈

感谢使用，有什么问题都可以反馈，我们会第一时间回复。

**Comment by DaYang816** [comment]
> > > > 
> > > 
> > > 
> > > 你可以参考新的来写，就可以用了，后面考虑下单独抽离出来一个组件，方便大家使用
> > 
> > 
> > 个人感觉已经很不错了，只要重写一下方法就能随便用了，不像别的要固定格式啥的，还要嵌套哈哈
> 
> 感谢使用，有什么问题都可以反馈，我们会第一时间回复。

我还有个issues 能帮我回答么，最好能优化一下我也不知道怎么优化了这个

**Comment by DaYang816** [comment]
> hotcity 网站上及时没有更新，可以参考demo例子。 List hotCityList = []; hotCityList.addAll([ BrnSelectCityModel(名称:“北京”), BrnSelectCityModel(名称:“广州市”), BrnSelectCityModel(名称:“成都市”), BrnSelectCityModel(名称:“深圳市”), BrnSelectCityModel(名称:“广州市”)杭州市”）， BrnSelectCityModel（名称：“武汉市”）， ]）； return BrnSingleSelectCityPage( appBarTitle: '城市单选', hotCityTitle: '这里是推荐城市', hotCityList: hotCityList, );

非常抱歉打扰你， 我想请问一下，城市选择器空页面如何修改  看到源码有个_BrnSingleSelectCityPageState类里面写了一个Widget _noDataWidget  但是我不知道如何去替换它

**Comment by leftcoding** [comment]
> > hotcity 网站上及时没有更新，可以参考demo例子。 List hotCityList = []; hotCityList.addAll([ BrnSelectCityModel(名称:“北京”), BrnSelectCityModel(名称:“广州市”), BrnSelectCityModel(名称:“成都市”), BrnSelectCityModel(名称:“深圳市”), BrnSelectCityModel(名称:“广州市”)杭州市”）， BrnSelectCityModel（名称：“武汉市”）， ]）； return BrnSingleSelectCityPage( appBarTitle: '城市单选', hotCityTitle: '这里是推荐城市', hotCityList: hotCityList, );
> 
> 非常抱歉打扰你， 我想请问一下，城市选择器空页面如何修改 看到源码有个_BrnSingleSelectCityPageState类里面写了一个Widget _noDataWidget 但是我不知道如何去替换它

目前，这个空widget自定义没有开放出去

**Comment by DaYang816** [comment]
> 不开放也不能这么展示吧。。。

![微信图片_20220921105159](https://user-images.githubusercontent.com/43984550/191403608-44150a4b-edeb-4116-b2eb-ebe0b1904d50.jpg)

**Comment by DaYang816** [comment]
> > > hotcity 网站上及时没有更新，可以参考demo例子。 List hotCityList = []; hotCityList.addAll([ BrnSelectCityModel(名称:“北京”), BrnSelectCityModel(名称:“广州市”), BrnSelectCityModel(名称:“成都市”), BrnSelectCityModel(名称:“深圳市”), BrnSelectCityModel(名称:“广州市”)杭州市”）， BrnSelectCityModel（名称：“武汉市”）， ]）； return BrnSingleSelectCityPage( appBarTitle: '城市单选', hotCityTitle: '这里是推荐城市', hotCityList: hotCityList, );
> > 
> > 
> > 非常抱歉打扰你， 我想请问一下，城市选择器空页面如何修改 看到源码有个_BrnSingleSelectCityPageState类里面写了一个Widget _noDataWidget 但是我不知道如何去替换它
> 
> 目前，这个空widget自定义没有开放出去

这就很难受了。。空页面是这种的，根本不能用了

**Comment by leftcoding** [comment]
> 

不好意思，我们会尽快迭代更新。

**Comment by zhoujuanjuan** [comment]
空页面的展位图已替换，感谢反馈
