### ISSUE TITLE
BrnTextSelectFormItem的布局字看上去是偏上的

### ISSUE THREAD

**Issue by DaYang816** [LianjiaTech/bruno#330]
BrnTextSelectFormItem的布局字看上去是偏上的，希望作者改一下，源码中有个布局是这样的，我不知道我的想法对不对，因为我是个初学者，其中的crossAxisAlignment: CrossAxisAlignment.start,导致的偏上，整体看上起很难受，给不了图片，唉不然很明显看出来往上面偏了。希望能改进，希望能做出国产的好用的组件库。
```
Widget build(BuildContext context) {
    return Container(
      color: widget.themeData!.backgroundColor,
      padding: BrnFormUtil.itemEdgeInsets(widget.themeData!),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          widget._isAutoLayout ?? false
              ? _buildAutoLayoutTitleWidget(context)
              : _buildTitleWidget(context),

          // 副标题
          BrnFormUtil.buildSubTitleWidget(widget.subTitle, widget.themeData!),

          // 错误提示
          BrnFormUtil.buildErrorWidget(widget.error, widget.themeData!)
        ],
      ),
    );
  }
```

**Comment by leftcoding** [comment]
如果方便的话，请附上视频或者截图，已经使用的sdk版本号，bruno的版本等，方便排查问题，谢谢。

**Comment by DaYang816** [comment]
> 如果方便的话，请附上视频或者截图，已经使用的sdk版本号，bruno的版本等，方便排查问题，谢谢。

这，，我好像不会传图 ，可以留个邮箱？

**Comment by DaYang816** [comment]
![Snipaste_2022-09-18_19-32-34](https://user-images.githubusercontent.com/43984550/190899952-b19f2b3d-8ab1-470d-a0a4-01a23eaf9b28.png)
每个字的下面都是有个空白的
![Snipaste_2022-09-18_19-33-58](https://user-images.githubusercontent.com/43984550/190900003-dcce10f9-1c86-43fc-954a-433b028e217f.png)
就导致了 上面短了，下面空太大了，期初我以为是我的分割线问题，但是去掉之后才发现是组件的有个留白，不知道这个能讲清楚么

**Comment by DaYang816** [comment]
> 如果方便的话，请附上视频或者截图，已经使用的sdk版本号，bruno的版本等，方便排查问题，谢谢。

已提供图片，不知道是否可以讲清楚问题，谢谢你的回复。

**Comment by leftcoding** [comment]
嗯，已经发现问题了，并解决了。晚点会提pr，到时候关注下

**Comment by DaYang816** [comment]
> 嗯，已经发现问题了，并解决了。晚点会提pr，到时候关注下

啊啊啊  谢谢  谢谢  我能更新到么

**Comment by leftcoding** [comment]
晚点，我提一个pr。要等他们合并，你如果不记得话，明天应该就可以了

**Comment by DaYang816** [comment]
> 

插件会自动更新么   不理解这个机制  项目中如何去更新呢     谢谢 非常开心能被采纳

**Comment by leftcoding** [comment]
> > 
> 
> 插件会自动更新么 不理解这个机制 项目中如何去更新呢 谢谢 非常开心能被采纳

一般会发布新版本，你就可以更新到新版本就行了

**Comment by DaYang816** [comment]
> 

谢谢你，我知道，到时候项目更新一下版本就行了，十分感谢你的回复，对于初学者来讲收到issues回复真的很棒。

**Comment by leftcoding** [comment]
> > 
> 
> 谢谢你，我知道，到时候项目更新一下版本就行了，十分感谢你的回复，对于初学者来讲收到issues回复真的很棒。

如果你着急的话，可以先这样处理：BrnTextSelectFormItem(
              title: "证件类型",
             // 新增这行
              themeData: BrnFormItemConfig(errorPadding: EdgeInsets.zero),
            )

**Comment by DaYang816** [comment]
> > > 
> > 
> > 
> > 谢谢你，我知道，到时候项目更新一下版本就行了，十分感谢你的回复，对于初学者来讲收到issues回复真的很棒。
> 
> 如果你着急的话，可以先这样处理：BrnTextSelectFormItem( title: "证件类型", // 新增这行 themeData: BrnFormItemConfig(errorPadding: EdgeInsets.zero), )

十分感谢
