### ISSUE TITLE
主题定制背景色等都没生效

### ISSUE THREAD

**Issue by Code-Clem** [LianjiaTech/bruno#332]
在main.dart中定制了主题，但除了BrnDialogConfig中的radius生效了，其他背景色都没生效，烦请问下，这个是啥原因啊。
BrnInitializer.register(
        allThemeConfig: BrnAllThemeConfig(
            // 全局配置
            commonConfig: BrnCommonConfig(
              brandPrimary: BaseColors.COLOR_PRIMARY,
              fillBase: BaseColors.COLOR_6F7F90,
              fillBody: BaseColors.COLOR_6F7F90,
            ),
            // dialog配置
            dialogConfig: BrnDialogConfig(
                radius: 150, backgroundColor: BaseColors.COLOR_6F7F90)));

**Comment by xyhuangjia** [comment]
> > 在main.dart中定制了主题，但除了BrnDialogConfig中的radius生效了，其他背景色都没生效，烦请问下，这个是啥原因啊。 BrnInitializer.register( allThemeConfig: BrnAllThemeConfig( // 全局配置 commonConfig: BrnCommonConfig( brandPrimary: BaseColors.COLOR_PRIMARY, fillBase: BaseColors.COLOR_6F7F90, fillBody: BaseColors.COLOR_6F7F90, ), // dialog配置 dialogConfig: BrnDialogConfig( radius: 150, backgroundColor: BaseColors.COLOR_6F7F90)));
> 
> 请附上视频或者截图、flutter sdk 版本、bruno 版本，方便排查问题。

我的主题配置好像也没有生效，我看示例代码里面也没有调用的地方。

[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.3.1 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.3.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (2 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc4)
    • Android SDK at /Users/huangj/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

版本为3.x

**Comment by zhoujuanjuan** [comment]
你好，参照你的配置，我们在main.dart 设置后是生效的，现在是否还存在问题，如存在请将使用的上下文代码和详细截图贴给我们，以便排查

**Comment by laowangDemon** [comment]
背景色相关无效，文字颜色管用，很奇怪IMG_8037 2.HEICIMG_8036.HEIC

**Comment by laowangDemon** [comment]
文字颜色变了，背景色无效，背景色和组件背景色都设置red了
![IMG_8037 2](https://user-images.githubusercontent.com/35515568/196881380-990bf414-8cc0-45c6-8034-004a5579c9a3.jpg)
![IMG_8036](https://user-images.githubusercontent.com/35515568/196881405-54840ea8-2f92-429e-b8d0-491b42d2c640.jpg)

**Comment by laowangDemon** [comment]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/35515568/196882794-87afa194-46e6-411a-9875-6d7f7a1d2059.png">
直接修改了插件的组件背景色和页面背景色也无效，难道我们理解的组件背景色，与你们的背景色不是一个，我理解的背景色是这个所属村庄后面那个白色背景色，不知道我是否理解正确

**Comment by fg2q1q3q** [comment]
大概率是因为全局配置主题色后，在materialApp里又配置了ThemeData
