### ISSUE TITLE
官网ios版本示例app无法下载

### ISSUE THREAD

**Issue by 826327700** [LianjiaTech/bruno#339]
官网ios版本示例app无法下载

**Comment by zhoujuanjuan** [comment]
您好，官网 ios 包确实有问题，我们会尽快更新官网二维码，感谢反馈

**Comment by k3v1n-uncle** [comment]
不能安装？iPhone6安装不了，安装完事灰色打不开

**Comment by leftcoding** [comment]
> 不能安装？iPhone6安装不了，安装完事灰色打不开

我们会尽快更新

**Comment by yorickshan** [comment]
麻烦尽快更新，目前还是安装不了

**Comment by hanwenbo** [comment]
我也是 从去年开始就没再下载成功过了

**Comment by zhoujuanjuan** [comment]
你好，由于iOS证书的限制，为减少不必要的资源消耗，我们将下线 iOS Demo ，如需要示例可以查看[官网](https://bruno.ke.com/page/demo)，或者 fork bruno  运行查看，感谢关注
