### ISSUE TITLE
Brntabbar 距离过长问题

### ISSUE THREAD

**Issue by zhaoweiguo5505** [LianjiaTech/bruno#340]
brntab bar 设置4个的时候 同时设置 mode 为  BrnTabBarBadgeMode.origin 禁止滑动。就会出现距离越界 

The following assertion was thrown during layout:
A RenderFlex overflowed by 4.8 pixels on the right.

附上代码
    tabs.add(BadgeTab(text: "All",topText: "1"));
    tabs.add(BadgeTab(text: "Order",topText: "2"));
    tabs.add(BadgeTab(text: "Order received".replaceAll(' ', "\u200B"),topText: "2"));
    tabs.add(BadgeTab(text: "Completed",topText: "2"));

 BrnTabBar(tabs:logic.tabs.value,controller:logic.tabController,hasIndex: true,mode: BrnTabBarBadgeMode.origin,isScroll: false,);

**Comment by leftcoding** [comment]
请按模板提问，谢谢

**Comment by violinday** [comment]
问题已复现，将在后续版本中优化overflow 效果，感谢反馈~

**Comment by zhoujuanjuan** [comment]
你好，问题已修复，感谢反馈https://github.com/LianjiaTech/bruno/pull/370
