### ISSUE TITLE
BrnToast

### ISSUE THREAD

**Issue by mrchenmo** [LianjiaTech/bruno#341]
BrnToast的getVerticalOffset方法，有两个字段的值是不是取错了，还是逻辑上就是要求这样写的？

![WMUFPQ~(S@WAL%2 GA{HIWQ](https://user-images.githubusercontent.com/18020929/192476219-4ff77f99-877e-405d-9ef7-200d90f589c0.png)

**Comment by leftcoding** [comment]
感谢反馈，确实是写反了

**Comment by violinday** [comment]
pr #343 已解决，issue 暂时关闭。
再次感谢反馈~
