### ISSUE TITLE
[Optimize]: 点击 BrnTextInputFormItem 组件的 padding 能够获取焦点 

### ISSUE THREAD

**Issue by lemos1235** [LianjiaTech/bruno#349]
## 优化建议

**1、优化描述**

目前 BrnTextInputFormItem 组件是在 TextField 之外包裹一个 padding，其中上下padding是 14，左右padding是 20 。
这样会导致当用户点击到padding区域（见下方附图黄色标记处），无法触发focus 并弹出键盘输入框，这样体验非常不好。

**2、关联组件**

BrnTextInputFormItem 

**3、具体优化建议**

建议 padding 放到 TextField 之中，作为内部 padding。 

**4、运行环境（非必填）**

* 运行设备 pixel4
* 系统 android
* Bruno 版本 3.0.0

**5、附加信息**

![image](https://user-images.githubusercontent.com/23135552/194685155-1dc0e32f-d600-453b-be5e-1c1fc61aecd6.png)

**Comment by leftcoding** [comment]
收到建议，会第一时间进行优化。

**Comment by zhoujuanjuan** [comment]
具体原因可参见PR comment
