### ISSUE TITLE
折线图计算path时出现NaN

### ISSUE THREAD

**Issue by xufengzz** [LianjiaTech/bruno#359]
* Bruno 版本
2.0-3.0都有该问题

只要组装的DBDataNodeModel 值包含多个相同值时。计算path会NaN导致报错
折线图计算path时出现NaN

复现步骤  
折线图无法实现 多个月份 展示0的效果
![25](https://user-images.githubusercontent.com/43258342/195994326-3563e815-80d7-403b-8481-9c6f8f6543b7.png)

**Comment by leftcoding** [comment]
给个最小的demo

**Comment by xufengzz** [comment]
> 给个最小的demo
直接照着官网 demo写的  看下是bug吗

```四、效果及代码展示：
效果一 （单条线、带阴影）
```

[flutter_demo.zip](https://github.com/LianjiaTech/bruno/files/9801200/flutter_demo.zip)

**Comment by zhoujuanjuan** [comment]
还请贴图表明，什么场景需要多个相同的值

**Comment by zasray** [comment]
> > 还请贴图表明，什么场景需要多个相同的值
> 
> 随便几个月没数据。就是0 不很正常嘛、或者一年中几个月没数据是0也会报错

有理

**Comment by zhoujuanjuan** [comment]
有道理，如果一张有效的折线图是应该 x，y轴并存的，所以建议当数据都为0时，折线图会展示异常，当然组件内部也应该有提示关于这点的限制，我们已经在https://github.com/LianjiaTech/bruno/pull/364/files加上，感谢反馈
