### ISSUE TITLE
日期时间选择组件文档中回调的描述错误

### ISSUE THREAD

**Issue by YueSeSuiFeng** [LianjiaTech/bruno#360]
## 优化建议

标题格式：[Optimize]: 优化简介

内容需包含：

**1、优化描述** 日期时间选择组件文档中回调的描述错误

**2、关联组件**BrnDatePicker 

**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息
![QQ截图20221018152719](https://user-images.githubusercontent.com/26158197/196366008-ec3d15a5-8a66-4c19-a54d-c530f7547053.png)

**Comment by leftcoding** [comment]
感谢反馈
