### ISSUE TITLE
关于BrnToast中onDismiss属性，是如何使用的？怎么在点击toast消失呢而不是设置时间长短来控制？请告诉一下

### ISSUE THREAD

**Issue by kite424** [LianjiaTech/bruno#363]
## 优化建议

标题格式：[Optimize]: 优化简介

内容需包含：

**1、优化描述**

**2、关联组件**

**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by zhoujuanjuan** [comment]
你好，从 Toast 本身交互属性是不支持点击消失的，如果想要点击消失建议使用popwindow 或者 dialog 实现
