### ISSUE TITLE
BrnMultiDataPicker弹窗的“确定”按钮和“取消”按钮点击事件范围太小了，建议增大一点，手指有时候点不上按钮，很难受

### ISSUE THREAD

**Issue by yaochangliang159** [LianjiaTech/bruno#369]
## 优化建议

优化内容: 所有Picker类的弹窗的确认取消按钮的点击范围太小了，我感觉你们把点击事件只是加到那个Text文字上了，应该在Text外面包一个Container，把点击事件加到Container上，然后把Container的宽高调高一点，这样点击范围比较大，不然所有的Picker类的弹窗 确定取消按钮有时候手指头点不上，难受的很！

内容需包含：

**1、所有Picker类的弹窗的确认取消按钮的点击范围太小了，我感觉你们把点击事件只是加到那个Text文字上了，应该在Text外面包一个Container，把点击事件加到Container上，然后把Container的宽高调高一点，这样点击范围比较大，不然所有的Picker类的弹窗 确定取消按钮有时候手指头点不上，难受的很！**

**2、关联组件 BrnMultiDataPicker等等。。。**

**3、运行环境（非必填）**

* 运行设备      华为nova9
* 系统             鸿蒙3.0.0
* Bruno 版本  3.1.0
* Flutter Doctor 信息
<img width="585" alt="2222" src="https://user-images.githubusercontent.com/13497352/202135018-95a7d34c-121e-4937-a849-cd1780adebc4.png">
 
* 
* 

**5、附加信息**
<img width="490" alt="1111" src="https://user-images.githubusercontent.com/13497352/202134963-90ab82e5-2f6c-47f5-8bdf-cc99e8dff691.png">

**Comment by zhoujuanjuan** [comment]
确实，我们跟交互确认下修改

**Comment by violinday** [comment]
#383  已提交修复，将在近期版本上线，暂时关闭该 issue， 感谢反馈～
