### ISSUE TITLE
BadgeTab key 参数没有真正传入widget使用

### ISSUE THREAD

**Issue by lgGuo** [LianjiaTech/bruno#375]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

问题的描述，请尽量使用简短、准确的语言

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by leftcoding** [comment]
能不能粘贴代码。或者截图

**Comment by lgGuo** [comment]
![image](https://user-images.githubusercontent.com/13808932/208564852-b24f35da-64bf-4a39-8d05-ab29b6038011.png)

**Comment by violinday** [comment]
@lgGuo  经过检查，为无用参数，近期发版讲标记为废弃，后续版本将会删除，感谢反馈～

**Comment by lgGuo** [comment]
key 参数在某些场景是需要使用的，建议不要删除，直接传入底层widget 使用就行
