### ISSUE TITLE
1.0.0版本 点击底部按钮无法关闭弹窗 BrnDialogManager.showConfirmDialog

### ISSUE THREAD

**Issue by ss876079056** [LianjiaTech/bruno#38]

**Comment by violinday** [comment]
组件默认不处理 导航（push、pop）操作。
可以在 onTap、onConfirm等回调中添加 `Navigator.pop(context);` 关闭弹窗。
: )

**Comment by hexintao** [comment]
安卓手机如果需要响应系统的返回按键关闭弹窗，需要在弹窗的外层监听 WillPopScope 的 onWillPop 事件处理

**Comment by violinday** [comment]
已关闭该 issue，如有问题再反馈~ 
: )
