### ISSUE TITLE
请教一下,为什么左右两个BrnNumberInfoItemModel 会出现不居中问题

### ISSUE THREAD

**Issue by mwupeng** [LianjiaTech/bruno#380]
<img width="631" alt="微信截图_20221221151848" src="https://user-images.githubusercontent.com/47802998/208844242-c809ddf9-8f6a-4227-8338-c89ad3468da8.png">

**Comment by mwupeng** [comment]
<img width="322" alt="微信截图_20221221152431" src="https://user-images.githubusercontent.com/47802998/208845149-598c8b8b-407a-4539-97a0-0dd292ac416c.png">

**Comment by violinday** [comment]
该问题已在 pr #386 中修复，将在后续版本中上线。 感谢反馈～
