### ISSUE TITLE
type 'Null' is not a subtype of type 'BrnIntl'

### ISSUE THREAD

**Issue by Story5** [LianjiaTech/bruno#391]
## 问题提交

标题格式：[BUG]: 问题简介
```bash
type 'Null' is not a subtype of type 'BrnIntl'
```
内容需包含：

**1、BUG 描述**

本地化报错

**2、复现步骤**
控制台输出
```bash
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building BrnTextInputFormItem(dirty, dependencies: [_LocalizationsScope-[GlobalKey#bf07c]], state: BrnTextInputFormItemState#a4080):
type 'Null' is not a subtype of type 'BrnIntl'

The relevant error-causing widget was: 
  BrnTextInputFormItem BrnTextInputFormItem:file:///Users/Gitee/zqne/lib/widgets/pages/device/install/device_install.dart:837:30
When the exception was thrown, this was the stack: 
#0      BrnIntl.of (package:bruno/src/l10n/brn_intl.dart:42:26)
#1      BrnTextInputFormItemState.build (package:bruno/src/components/form/items/general/brn_text_input_item.dart:214:55)
```
相关代码
```dart
/// 获取[BrnIntl]实例
  static BrnIntl of(BuildContext context) {
    return Localizations.of(context, BrnIntl);
  }
```
**3、期望行为**
不报错

**4、运行环境**

* 运行设备 `honor 6A`
* 系统 `7.0`
* Bruno 版本 `3.2.0`
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息
![IMG_1371](https://user-images.githubusercontent.com/15045641/210307756-b133cce8-ebcc-4e1a-b771-ba36ec4e273d.JPG)

**Comment by ldk577** [comment]
文件 main.dart -> MaterialApp 的属性 localizationsDelegates 的值设置为 [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          BrnLocalizationDelegate.delegate,
        ]

**Comment by leftcoding** [comment]
添加国际化初始化。BrnLocalizationDelegate.delegate

**Comment by Story5** [comment]
@ldk577 @leftcoding 感谢,可用,已解决
