### ISSUE TITLE
[BUG]: Badge is imported from both

### ISSUE THREAD

**Issue by shi-lai-mu** [LianjiaTech/bruno#396]
## 问题提交
使用BrnBottomTabBar时遇到以下问题

../../../.pub-cache/hosted/pub.dev/bruno-2.2.0/lib/src/components/tabbar/normal/brn_tab_bar.dart:463:17: Error: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'.
                Badge(
                ^^^^^

<img width="1771" alt="image" src="https://user-images.githubusercontent.com/45140991/211232046-bd273b9b-e88c-4607-abdf-d4a7ffc90a79.png">

**2、复现步骤**

      1：实现底部导航
            bottomNavigationBar: BrnBottomTabBar(
              fixedColor: Colors.blue,
              currentIndex: _selectedBarIndex,
              badgeColor: Colors.red,
              items: const <BrnBottomTabBarItem>[
                BrnBottomTabBarItem(
                    icon: Icon(Icons.home),
                    title: Text("首页1"),
                    badgeNo: null,
                    activeIcon: Icon(Icons.home_filled)),
                BrnBottomTabBarItem(
                    icon: Icon(Icons.home),
                    title: Text("首页2"),
                    badgeNo: null,
                    activeIcon: Icon(Icons.home_filled)),
              ],
            ),
       2：热重载后运行报错 Badge is imported from both

**3、期望行为**
不报错正常运行

**4、运行环境**

* 运行设备
   iPhone 14 Pro Max
* 系统
   MacOs 13.0.1 (22A400)
* Bruno 版本
   Bruno 2.2.0
* Flutter Doctor 信息
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel master, 3.7.0-15.0.pre.11, on macOS 13.0.1 22A400 darwin-arm64, locale zh-Hans-CN)
    [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    [✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2021.3)
    [✓] VS Code (version 1.74.2)
    [✓] Connected device (3 available)
    [✓] HTTP Host Availability

**5、附加信息**
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/45140991/211232653-55af29cd-119c-427b-9fa2-7d03aed6c49e.png">
<img width="822" alt="image" src="https://user-images.githubusercontent.com/45140991/211232652-505b7460-89ac-4664-bf20-0ce3f1157385.png">

包括视频、图片等补充信息

**Comment by leftcoding** [comment]
improt 'package:flutter/material.dart' hide  Badge;

**Comment by shi-lai-mu** [comment]
> improt 'package:flutter/material.dart' hide Badge;

是修改本地的brn_tab_bar.dart吗，在应该不是最好的选择吧？

**Comment by leftcoding** [comment]
看问题，跟 material 库里面的 Badge 重复，你如果引入 bruno 的 Badge，可以隐藏 material 库里面的 Badge

**Comment by shi-lai-mu** [comment]
> BrnBottomTabBar

引入的是bruno 的 BrnBottomTabBar，BrnBottomTabBar 的 brn_tab_bar.dart 里的 Badge 重复报错了 [5、附加信息] 的第一张图是brn_tab_bar.dart的，项目中暂时没使用  bruno 的 Badge

**Comment by violinday** [comment]
@shi-lai-mu  flutter 在后续版本中 增加了 Badge 组件，目前 Bruno 优先适配 Flutter stable 版本，暂时未适配未发布的版本。
后续适配 flutter 新版本时考虑去除 badge 库依赖，替换为官方组件。

ps. 日常开发推荐使用官方稳定版本～

**Comment by wwg90** [comment]
请问你这个问题解决了吗？ 我现在hide 哪个都没法运行

**Comment by shi-lai-mu** [comment]
> 请问你这个问题解决了吗？ 我现在hide 哪个都没法运行

我切换flutter至稳定版，暂时解决了这个问题

**Comment by zhoujuanjuan** [comment]
3.3.0 版本已发布解决，带来的不便深感抱歉
