### ISSUE TITLE
picker运行时报错

### ISSUE THREAD

**Issue by shengzhaotong** [LianjiaTech/bruno#401]
调用picker弹窗时报错如下：
The following NoSuchMethodError was thrown building BrnBottomPickerWidget(dirty, dependencies: [_LocalizationsScope-[GlobalKey#bf2cb]], state: BrnBottomPickerWidgetState#29ea4(tickers: tracking 1 ticker)):
The getter 'localizedResource' was called on null.
Receiver: null
Tried calling: localizedResource

* 运行设备
* RedMi K30 Pro
* bruno: ^3.2.0

**Comment by shengzhaotong** [comment]
已解决，官网中给出的示例代码缺少了confirm和cancel这两个参数

**Comment by shengzhaotong** [comment]
showDatePicker显示日期的时候月份显示不出来

**Comment by violinday** [comment]
> showDatePicker显示日期的时候月份显示不出来

感谢反馈～
麻烦提供下关键代码、错误日志或截图，方便我们查找问题

**Comment by shengzhaotong** [comment]
报错如下图：

上面的截图运行环境为Windows平台，安卓真机运行环境为RedMi K30 Pro，也会出现同样的错误。
顺便问一下bruno.ke.com这个文档什么时候会更新啊，上面的好多demo都是错的
（报错的示例代码在附件中）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LianjiaTech/bruno"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月17日(星期二) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LianjiaTech/bruno] picker运行时报错 (Issue #401)





  
showDatePicker显示日期的时候月份显示不出来
  
感谢反馈～
 麻烦提供下关键代码、错误日志或截图，方便我们查找问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

bruno_date_picker_test.zip (85.01M, 2023年02月16日 18:44 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7f333863ded8999c2d128b3543380449035601065008045e1d525a53071502055407155a0001034b56555953530b500204575e50652236044246560c3a5c5712556c480a065353146f475d1011164c0f403305&code=038ce86f

**Comment by leftcoding** [comment]
添加国际化依赖，代码如下：
```
dependencies:
  flutter:
    sdk: flutter
  bruno: ^3.2.0
  flutter_localizations: # 新增这行
    sdk: flutter
```
在 Main App 添加如下代码：
```
return MaterialApp(
      // 新增
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        BrnLocalizationDelegate.delegate,
      ],
     // 新增
      supportedLocales: const [
        Locale('en', 'US'),
        Locale('zh', 'CN'),
      ],
      home: ...
    );
```
