### ISSUE TITLE
Badge 有冲突了，大神怎么解决的？

### ISSUE THREAD

**Issue by wwg90** [LianjiaTech/bruno#402]
Error (Xcode): ../../.pub-cache/hosted/pub.flutter-io.cn/bruno-3.2.0/lib/src/components/tabbar/normal/brn_tab_bar.dart:399:11: Error: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'.

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).

**Comment by leftcoding** [comment]
临时解决办法，我们目前只做了flutter 稳定版本的兼容。  
bruno:
    git:
      url: "git@github.com:LianjiaTech/bruno.git"
      ref: "3.7.x"

**Comment by zhoujia456888** [comment]
不知道是我 Flutter版本还是写法的问题。。。我的要这样才可以。虽然看上去意思是一样的。（git配置问题？）
`
  bruno:
    git:
      url: https://github.com/LianjiaTech/bruno.git
      ref: 3.7.x
`

**Comment by leftcoding** [comment]
> 不知道是我 Flutter版本还是写法的问题。。。我的要这样才可以。虽然看上去意思是一样的。（git配置问题？）(区别在于没有分号，并将git@换成了https)
> 
> ```
>  bruno:
>     git:
>       url: https://github.com/LianjiaTech/bruno.git
>       ref: 3.7.x
> ```

都可以，

**Comment by wwg90** [comment]
好的，谢谢，我回头试试我的这些改行不行

**Comment by zhoujuanjuan** [comment]
3.3.0 版本已发布解决，带来的不便深感抱歉
