### ISSUE TITLE
Flutter 3.7.0  'Badge'兼容问题啥时候解决？

### ISSUE THREAD

**Issue by Demon-liao** [LianjiaTech/bruno#406]
## 问题提交

标题格式：[BUG]: Flutter 3.7.0  'Badge'兼容问题啥时候解决？

内容需包含：

**1、BUG 描述**
现在flutter3.7.0已经是稳定版本了，升级后出现这个问题。啥时候可以正式解决？

 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'.

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by leftcoding** [comment]
参考这个：https://github.com/LianjiaTech/bruno/issues/402

**Comment by zhoujuanjuan** [comment]
3.3.0 版本已发布解决，带来的不便深感抱歉
