### ISSUE TITLE
日历控件报错

### ISSUE THREAD

**Issue by Demon-liao** [LianjiaTech/bruno#408]
## 问题提交

标题格式：[BUG]: 使用3.7.x版本的日历控件报错

内容需包含：

**1、BUG 描述**
日历控件的月份没法显示出来

![image](https://user-images.githubusercontent.com/2654683/215323348-aa0e2631-0f41-4a13-9071-ea2c7a08142c.png)
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/2654683/215323359-5b6e89b3-97d4-4c38-81ab-806a77ecc323.png">

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by leftcoding** [comment]
参考： https://github.com/LianjiaTech/bruno/issues/391
