### ISSUE TITLE
所有的文本框Flutter3.7版本不支持 magnifierConfiguration  长按后会一直显示放大镜

### ISSUE THREAD

**Issue by supermebing** [LianjiaTech/bruno#409]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

所有的文本框Flutter3.7版本不支持 magnifierConfiguration  长按后会一直显示放大镜

**2、复现步骤**
输入框长按 会显示一个放大镜  无法关闭
**3、期望行为**
长按完成后 隐藏放大镜 
**4、运行环境**

* 运行设备 iphone12
* 系统 ios 16.3
* Bruno 版本 3.2.0
* Flutter Doctor 信息
* [✓] Flutter (Channel stable, 3.7.0, on macOS 11.7.2 20G1020 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**5、附加信息**

包括视频、图片等补充信息

**Comment by sineom-1** [comment]
可以查看下 https://github.com/flutter/flutter/issues/119711

**Comment by ervinsae** [comment]
同样出现

**Comment by zhoujuanjuan** [comment]
感谢[sineom-1](https://github.com/sineom-1) 回复，该问题解决方案请见官方issue
