### ISSUE TITLE
Badge 冲突问题

### ISSUE THREAD

**Issue by tuke-code** [LianjiaTech/bruno#426]
## 问题提交

标题格式：[BUG]: 问题简介
../../.pub-cache/hosted/pub.flutter-io.cn/bruno-3.2.0/lib/src/components/tabbar/normal/brn_tab_bar.dart:399:11: Error: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'.
          Badge(
          ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/bruno-3.2.0/lib/src/components/tabbar/normal/brn_tab_bar.dart:469:17: Error: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'.
                Badge(
                ^^^^^
Target kernel_snapshot failed: Exception

内容需包含：

**1、BUG 描述**
 引用后出现这个问题 使用了BrnIconButton

**2、复现步骤**

**3、期望行为**

**4、运行环境**
flutter 3.7.3 * androoid studio
* 运行设备
 mac book pro m1 pro
* 系统
* macos 
* Bruno 版本
* 3.2.0
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by leftcoding** [comment]
请升级最新版本
