### ISSUE TITLE
Context: Found this candidate, but the arguments don't match.

### ISSUE THREAD

**Issue by lexoops** [LianjiaTech/bruno#431]
## 问题提交

标题格式：Context: Found this candidate, but the arguments don't match.

内容需包含：

**1、BUG 描述**

/C:/Users/TUF/AppData/Local/Pub/Cache/hosted/pub.dev/bruno-3.3.0/lib/src/components/navbar/brn_appbar.dart:297:7: Error: No named parameter with the name 'brightness'.
      brightness: brightness ?? Brightness.light,
      ^^^^^^^^^^
/E:/flutter/packages/flutter/lib/src/material/app_bar.dart:177:3: Context: Found this candidate, but the arguments don't match.
  AppBar({
  ^^^^^^
Target kernel_snapshot failed: Exception

**2、复现步骤**

以下为我的依赖文件
![image](https://user-images.githubusercontent.com/33716494/226289940-f9874d30-c1d2-4e6e-898d-3b6bed51ae33.png)

**3、期望行为**
能正常使用

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息
![image](https://user-images.githubusercontent.com/33716494/226290192-e5c85890-4a14-410c-8e89-2686a22b3632.png)

**Comment by cybyob0** [comment]
我也遇到了，网上没有相关的信息（希望大佬们指点一二）~

<img width="747" alt="image" src="https://user-images.githubusercontent.com/129568979/229267889-836905ac-4c59-425f-a9dd-b293ccef8844.png">

**Comment by lexoops** [comment]
> 我也遇到了，网上没有相关的信息（希望大佬们指点一二）~
> 
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/129568979/229267889-836905ac-4c59-425f-a9dd-b293ccef8844.png">

已经弃了，用getwidget了

**Comment by Story5** [comment]
有人解决了么?

**Comment by Story5** [comment]
```
Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (2 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1
```
AppBar上已没有brightness属性

**Comment by BingKui** [comment]
这个bug是因为 Flutter 2.0 移除了这个属性，改用 Theme 了，所以可以把这个删了就行了。
可以用我修改后的库：https://github.com/BingKui/bruno.git
修改`pubspec.yaml` 文件:
```yaml
bruno:
    git:
      url: https://github.com/BingKui/bruno.git
```

即可解决报错问题。

**Comment by violinday** [comment]
Bruno 目前还没有升级适配 3.10.0 版本，近期会升级适配，解决该问题。
