### ISSUE TITLE
升级到3.2以后，所有的组件都报The getter 'localizedResource' was called on null. Receiver: null Tried calling: localizedResource错误

### ISSUE THREAD

**Issue by Wizhiai** [LianjiaTech/bruno#433]
## 问题提交

标题格式：[BUG]: 问题简介
升级到3.2以后，所有的组件都报The getter 'localizedResource' was called on null. Receiver: null Tried calling: localizedResource错误
内容需包含：

**1、BUG 描述**

升级到3.2以后，所有的组件都报错：
The getter 'localizedResource' was called on null. Receiver: null Tried calling: localizedResource

**2、复现步骤**

**3、期望行为**
运行正常
**4、运行环境**
flutter3.3.2
* 运行设备
* 系统
* Bruno 版本
* 最新版3.2版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by 183255536** [comment]
初始化语言
![image](https://github.com/LianjiaTech/bruno/assets/47137502/176df8cd-edcf-4c06-bc71-4a15203fe09a)
