### ISSUE TITLE
[BUG]: BrnNormalFormGroup属性tipLabel无效

### ISSUE THREAD

**Issue by Story5** [LianjiaTech/bruno#434]
**1、BUG 描述**

设置BrnNormalFormGroup 属性 tipLabel 无效

**2、复现步骤**

必现

**3、期望行为**

显示 ? 或 文案

**4、运行环境**

* Bruno 版本 `3.7.x`

**5、附加信息**

无

**Comment by zhoujuanjuan** [comment]
感谢反馈，该字段为无用字段，我们将删除，给您造成困扰深感抱歉
