### ISSUE TITLE
v3.2.0版本的日历组件

### ISSUE THREAD

**Issue by HumesFork** [LianjiaTech/bruno#435]
![image](https://user-images.githubusercontent.com/31274733/228705722-1caf0c20-97c5-4023-a1b1-211389418227.png)
![image](https://user-images.githubusercontent.com/31274733/228705758-cfc66ca4-b2f4-4fc6-885e-1a8ef047346b.png)
如图，flutter版本是3.3.10，引用日历组件后报该错误？

**Comment by leftcoding** [comment]
初始化下，国际化， 参考： https://github.com/LianjiaTech/bruno/issues/391

**Comment by HumesFork** [comment]
ok，解决了，感谢
