### ISSUE TITLE
升级flutter3.10.2最新版本不兼容，appBrn等组件少相关props

### ISSUE THREAD

**Issue by jiushicheng123** [LianjiaTech/bruno#460]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

问题的描述，请尽量使用简短、准确的语言

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by violinday** [comment]
是指 BrnAppBar 中 brightness 参数问题吗，这个问题已经收到反馈，预计 7 月中旬发版，升级适配最新版本，解决该问题。

**Comment by xiangBiaoOne** [comment]
> 
谢谢，感觉框架很好用，希望尽快升级

**Comment by lesany** [comment]
望尽快升级啊

**Comment by windhc** [comment]
支持

**Comment by violinday** [comment]
Bruno 3.4.0 已在 7.24 发布，版本已适配 Flutter 3.10。 感谢大家持续关注~   #468
