### ISSUE TITLE
[BUG]: Error: No named parameter with the name 'brightness'.

### ISSUE THREAD

**Issue by CodeHare** [LianjiaTech/bruno#463]
## [BUG]: Error: No named parameter with the name 'brightness'.

**1、BUG 描述**
- 环境
   
    -  bruno 版本是 3.3.0  
- 使用组件的时候，会报错，报错内容是 
![image](https://github.com/LianjiaTech/bruno/assets/57887470/3abb634e-ef81-4a64-b803-fa8b3dc51d7d)

**2、复现步骤**

**3、期望行为**
- 期待不报错正常的引用

**4、运行环境**
 -  flutter 3.7.11 版本

* 运行设备
![image](https://github.com/LianjiaTech/bruno/assets/57887470/02fc4bcd-0755-44cd-9bf6-8797d43e0fe2)

* 系统
- window 11 vscode editor

* Bruno 版本
- 3.3.0

* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by linhaosheng** [comment]
什么时候可以修复呢，这是直接劝退啊

**Comment by xiangBiaoOne** [comment]
赶快修复吧，我是刚了解到这个库就直接给劝退了？？？？

**Comment by violinday** [comment]
@linhaosheng @xiangBiaoOne @wolf-leo @CodeHare 
Bruno 3.4.0 已在 7.24 发布，版本已适配 Flutter 3.10。 感谢大家持续关注~   #468
