### ISSUE TITLE
 Error: 'Badge'

### ISSUE THREAD

**Issue by mazhengshui** [LianjiaTech/bruno#469]
## 问题提交

标题格式：[BUG]: 问题简介
Error (Xcode): ../../.pub-cache/hosted/pub.flutter-io.cn/bruno-3.3.0/lib/src/components/navbar/brn_appbar.dart:297:7: Error: No named parameter with the name 'brightness'.

内容需包含：

**1、BUG 描述**

在升级到flutter 3.10.0的时候 报 引入冲突

**2、复现步骤**

升级到3.10.0

**3、期望行为**
正常运行
**4、运行环境**
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2 22D49 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] Network resources
* 运行设备
* 系统
* Bruno 版本
* 3.3.0
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by mazhengshui** [comment]
希望尽快发布适配新版本，看评论说七月中旬左右发布新版本。

**Comment by violinday** [comment]
Bruno 3.4.0 已在 7.24 发布，版本已适配 Flutter 3.10  
#468
