### ISSUE TITLE
BrnTabBar badge设置无效

### ISSUE THREAD

**Issue by YouLiLiao** [LianjiaTech/bruno#487]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

BrnTabBar badge 设置无效，无法显示

**2、复现步骤**

无论设置badgeText或是badgeNum都无法显示

**3、期望行为**

**4、运行环境**
* 运行设备
Windows 10
* 系统
安卓
* Bruno 版本
3.4.2
* Flutter Doctor 信息
![image](https://github.com/LianjiaTech/bruno/assets/11286354/2553389d-367e-4029-91f8-13576c69a324)

**5、附加信息**

![image](https://github.com/LianjiaTech/bruno/assets/11286354/dd95bc68-b9ff-4f84-bce8-691b3b417c67)
![image](https://github.com/LianjiaTech/bruno/assets/11286354/28db2234-4895-4fc0-8219-9acfcd4a9537)

**Comment by zhoujuanjuan** [comment]
3.4.3版本已修复
