### ISSUE TITLE
空安全迁移认领

### ISSUE THREAD

**Issue by zhoujuanjuan** [LianjiaTech/bruno#49]
> 感谢参与迁移共建，在认领前请确保你认领的类别在[ project ](https://github.com/LianjiaTech/bruno/projects/1) todo 进度中

在确定没有其他人在迁移后回复：

申请迁移[组名] 
eg：apply migrate text 

请注意：我们建议一次迁移一类组件，因此认领建议一次认领一个类别

我们会按照时间顺序将对应 card 关联上申请的开发者
迁移工作预计将在 1月31号左右完成，如有特殊情况中途无法完成，还请在回复中及时同步我们~

最后，再次感谢大家参与 :heart:

**Comment by jojinshallar** [comment]
apply migrate text

**Comment by zhoujuanjuan** [comment]
> apply migrate text

text 已迁至空安全，换一个可好

**Comment by jojinshallar** [comment]
> 

所有component下的组件都已经完成null-safety的迁移，你随便选一个吧。（建议简单一点的，刚迁移完，有不少可以重构的地方）

**Comment by zhoujuanjuan** [comment]
> > 
> 
> 所有component下的组件都已经完成null-safety的迁移，你随便选一个吧。（建议简单一点的，刚迁移完，有不少可以重构的地方）

那  rating   :smiley::sunny:

**Comment by jojinshallar** [comment]
具体我需要怎么提交我的代码？
https://github.com/LianjiaTech/bruno/pull/42

**Comment by zhoujuanjuan** [comment]
> 具体我需要怎么提交我的代码？ #42

其它的 revert 只提交 brn_rating_star.dart 呢 😃

**Comment by jojinshallar** [comment]
> > 具体我需要怎么提交我的代码？ #42
> 
> 其它的 revert 只提交 brn_rating_star.dart 呢 😃

已经回退版本并单独提交brn_rating_star.dart了。
另外，最新的null-safety版本确定是没有问题的？我这里编译时，brn_delete_tag/brn_expandable_text/brn_search_text等都会因为 !或？使用不当在Run对话框里报warning。

**Comment by HappyImp** [comment]
> > > 具体我需要怎么提交我的代码？ #42
> > 
> > 
> > 其它的 revert 只提交 brn_rating_star.dart 呢 😃
> 
> 已经回退版本并单独提交brn_rating_star.dart了。 另外，最新的null-safety版本确定是没有问题的？我这里编译时，brn_delete_tag/brn_expandable_text/brn_search_text等都会因为 !或？使用不当在Run对话框里报warning。

这个exclude的问题，我已经提了 PR  还没合并..

**Comment by HappyImp** [comment]
还有什么组件没人搞的，我来弄吧 @zhoujuanjuan

**Comment by jojinshallar** [comment]
还有什么组件需要迁移的，继续~ @zhoujuanjuan

**Comment by zhoujuanjuan** [comment]
> 还有什么组件需要迁移的，继续~ @zhoujuanjuan

rating 已入 :clap:  ，下一个selectcity 可好 :blush:

**Comment by zhoujuanjuan** [comment]
> > 感谢参与迁移共建，在认领前请确保你认领的类别在[ project ](https://github.com/LianjiaTech/bruno/projects/1) todo 进度中
> 
> 在确定没有其他人在迁移后回复：
> 
> 申请迁移[组名] eg：apply migrate text
> 
> 请注意：我们建议一次迁移一类组件，因此认领建议一次认领一个类别
> 
> 我们会按照时间顺序将对应 card 关联上申请的开发者 迁移工作预计将在 1月31号左右完成，如有特殊情况中途无法完成，还请在回复中及时同步我们~
> 
> 最后，再次感谢大家参与 ❤️

参照以上，点击 project 查看，回复要迁移项~

**Comment by zhoujuanjuan** [comment]
> 还有什么组件没人搞的，我来弄吧 @zhoujuanjuan

参照头部内容，点击 project 查看TODO，选定后回复告知即可

**Comment by laiiihz** [comment]
apply migrate [card_title](https://github.com/LianjiaTech/bruno/projects/1#card-75544131)

**Comment by zhoujuanjuan** [comment]
> apply migrate [card_title](https://github.com/LianjiaTech/bruno/projects/1#card-75544131)

:ok_hand:  进度已更新

**Comment by zhoujuanjuan** [comment]
> > > > 具体我需要怎么提交我的代码？ #42
> > > 
> > > 
> > > 其它的 revert 只提交 brn_rating_star.dart 呢 😃
> > 
> > 
> > 已经回退版本并单独提交brn_rating_star.dart了。 另外，最新的null-safety版本确定是没有问题的？我这里编译时，brn_delete_tag/brn_expandable_text/brn_search_text等都会因为 !或？使用不当在Run对话框里报warning。
> 
> 这个exclude的问题，我已经提了 PR 还没合并..

正在review中...

**Comment by jojinshallar** [comment]
apply migrate noticebar

**Comment by laiiihz** [comment]
apply migrate calendar

**Comment by zhoujuanjuan** [comment]
> apply migrate noticebar

👌 进度已更新

**Comment by zhoujuanjuan** [comment]
> apply migrate calendar

👌 进度已更新

**Comment by zhoujuanjuan** [comment]
> apply migrate noticebar

代码已入，cool ~

**Comment by jojinshallar** [comment]
apply migrate radio

**Comment by zhoujuanjuan** [comment]
> apply migrate radio

:+1:  已更新

**Comment by jojinshallar** [comment]
apply migrate guide

**Comment by zhoujuanjuan** [comment]
> apply migrate guide

cool ~ 进度已更新

**Comment by jojinshallar** [comment]
apply migrate navbar and input

**Comment by laiiihz** [comment]
dialog组件依赖button组件，需要先迁移button组件
相关pr #20

**Comment by zhoujuanjuan** [comment]
> dialog组件依赖button组件，需要先迁移button组件 相关pr #20

是的，可以先迁移其它部分，这个提交我们跟进下处理

**Comment by donywan** [comment]
> > dialog组件依赖button组件，需要先迁移button组件 相关pr #20
> 
> 是的，可以先迁移其它部分，这个提交我们跟进下处理

已合并更新

**Comment by jojinshallar** [comment]
> apply migrate navbar and input

@zhoujuanjuan 继续？

**Comment by zhoujuanjuan** [comment]
> 

好，你来选 :grin:

**Comment by zhoujuanjuan** [comment]
> > apply migrate navbar and input
> 
> @zhoujuanjuan 继续？

好，你来选 :grin:

**Comment by zhoujuanjuan** [comment]
> > apply migrate navbar and input
> 
> @zhoujuanjuan 继续？

好，进度已更新 :grin:

**Comment by junlandroid** [comment]
@zhoujuanjuan 还有需要 migrate的组件？

**Comment by laiiihz** [comment]
@junlandroid 可以看一下这个 [project](https://github.com/LianjiaTech/bruno/projects/1)

**Comment by junlandroid** [comment]
apply migrate actionsheet

**Comment by zhoujuanjuan** [comment]
> apply migrate actionsheet

:ok_hand: 进度已更新，可以开始迁移

**Comment by jojinshallar** [comment]
apply migrate dialog

**Comment by laiiihz** [comment]
apply migrate charts

**Comment by zhoujuanjuan** [comment]
> apply migrate dialog

稍等，我们正在review上一个提交，待进入后通知  :fire:

**Comment by zhoujuanjuan** [comment]
> apply migrate dialog

上次提交已入，进度已更新，可以进行迁移，再次感谢共建 :sparkles:

**Comment by Nayuta403** [comment]
apply migrate gallery

**Comment by zhoujuanjuan** [comment]
> apply migrate gallery

准了，自己移去吧  :satisfied:

**Comment by zhoujuanjuan** [comment]
空安全迁移完成，感谢以上参与的开发者们 heartpulse:

**Comment by zhoujuanjuan** [comment]
空安全迁移完成，感谢以上参与的开发者们 :heartpulse

**Comment by XuJin186** [comment]
请问啥时候会发布空安全版本
