### ISSUE TITLE
https://bruno.ke.com/page/widgets/brn-bottom-button-panel

### ISSUE THREAD

**Issue by hanxiaofeng** [LianjiaTech/bruno#495]
访问这个组件，页面空白了

**Comment by zhoujuanjuan** [comment]
@violinday  3.4.0版本这个组件页面空白

**Comment by violinday** [comment]
@hanxiaofeng  已找到原因，后续会发布更新，可暂时切换到旧版本文档查看。
![image](https://github.com/LianjiaTech/bruno/assets/9434515/6530db61-def3-4408-a170-5a5f38827945)
