### ISSUE TITLE
Sketch 中不显示Flutter示例代码 

### ISSUE THREAD

**Issue by moxiaohao** [LianjiaTech/bruno#50]
Plugin 已经装上了  还需要怎么才做才能 展示代码么？

**Comment by violinday** [comment]
@moxiaohao
![image](https://user-images.githubusercontent.com/9434515/148176673-9db4e557-b89d-4786-9425-b4eea73e1ea4.png)

1、首先确保从 [Sketch 资源](https://bruno.ke.com/download/sketch) 下载并安装插件①，
2、使用② Sketch 组件库设计页面。
3、导出设计稿，具体导出步骤截图：
![image](https://user-images.githubusercontent.com/9434515/148176679-68314149-f915-49b7-ae24-f37748a2e7da.png)
4、使用浏览器打开导出的 index.html 文件即可。

PS: 组件文档关联跳转功能正在调试中，可稍后体验。 :)

**Comment by violinday** [comment]
@moxiaohao
![image](https://user-images.githubusercontent.com/9434515/148176673-9db4e557-b89d-4786-9425-b4eea73e1ea4.png)

1、首先确保从 [Sketch 资源](https://bruno.ke.com/download/sketch) 下载并安装插件①，
2、使用② Sketch 组件库设计页面。
3、导出设计稿，具体导出步骤截图：
![image](https://user-images.githubusercontent.com/9434515/148176679-68314149-f915-49b7-ae24-f37748a2e7da.png)
4、使用浏览器打开导出的 index.html 文件即可。

**Comment by zhoujuanjuan** [comment]
sketch 教程已优化为视频教程，如需要可前去查看https://bruno.ke.com/page/guide/sketch
