### ISSUE TITLE
BrnTabBar 设置 showMore: true 溢出BUG

### ISSUE THREAD

**Issue by error-code** [LianjiaTech/bruno#517]
**1、BUG 描述**

BrnTabBar 设置 showMore: true 溢出BUG

![微信截图_20231127152449](https://github.com/LianjiaTech/bruno/assets/19849369/38998801-27e9-409e-936f-a6efac2ae172)

**2、复现步骤**

Widget嵌套关系： Padding -> BrnTabBar
```
return Scaffold(
      appBar: AppBar(
        title: const Text('测试'),
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 10),
        child: BrnTabBar(
          controller: controller,
          mode: BrnTabBarBadgeMode.origin,
          labelPadding: const EdgeInsets.symmetric(horizontal: 10),
          showMore: true,
          tabs: [
            BadgeTab(text: '测试'),
            BadgeTab(text: '测试'),
            BadgeTab(text: '测试'),
            BadgeTab(text: '测试'),
            BadgeTab(text: '测试'),
            BadgeTab(text: '测试'),
            BadgeTab(text: '测试'),
          ],
        ),
      ),
    );
```

**3、期望行为**
不报溢出错误

**4、运行环境**
flutter 3.13.3
* 运行设备
 红米K40
* 系统
windows 11
* Bruno 版本
bruno: ^3.4.3
* Flutter Doctor 信息
[✓] Flutter (Channel stable, 3.13.3, on Microsoft Windows [版本 10.0.22621.2715], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.11)
[✓] Android Studio (version 2022.3)
[✓] Connected device (4 available)
[✓] Network resources

**5、附加信息**
![2222](https://github.com/LianjiaTech/bruno/assets/19849369/2f44fdbc-e978-4a8e-a48a-462790e18783)

包括视频、图片等补充信息

**Comment by qqworker** [comment]
还有如果是Expanded也有这个问题
