### ISSUE TITLE
引入broun文件就会报错

### ISSUE THREAD

**Issue by xuejingpeng** [LianjiaTech/bruno#52]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

../../flutter/.pub-cache/hosted/pub.flutter-io.cn/bruno-2.0.0/lib/src/components/form/items/group/element_expand_widget.dart:275:31: Error: The getter 'subhead' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
      ..end = theme.textTheme.subhead.color;

**2、复现步骤**

**3、期望行为**

**4、运行环境**
flutter 2.5.3
* 运行设备 
* 系统 
* Bruno 版本 2.0.0
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by violinday** [comment]
```
'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
..end = theme.textTheme.subhead.color;
```

从报错信息来看，报错位置在 Flutter text_theme.dart 文件中的 subhead 字段。
查看 flutter 源码，subhead 字段在 [1.13.8](https://github.com/flutter/flutter/blob/v1.16.3/packages/flutter/lib/src/material/text_theme.dart) 中已废弃，在[2.5.3 ](https://github.com/flutter/flutter/blob/v2.5.3/packages/flutter/lib/src/material/text_theme.dart) 中已见该字段删除。

可以检查本地 flutter 环境配置是否有问题。: )

**Comment by xuejingpeng** [comment]
> @xuejingpeng
> 
> ```
> 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
> ..end = theme.textTheme.subhead.color;
> ```
> 
> 从报错信息来看，报错位置在扑text_theme.dart文件中的小标题字段。 查看扑源码，小标题字段在[v1.13.8](https://github.com/flutter/flutter/blob/v1.16.3/packages/flutter/lib/src/material/text_theme.dart)中已废弃，在[2.5.3](https://github.com/flutter/flutter/blob/2.5.3/packages/flutter/lib/src/material/text_theme.dart)中已见该字段删除。
> 
> 可以检查本地flutter 环境配置是否有问题。:)

就是2.5.3删了该字段了，这个太久没更新，能否更一个版本出来

**Comment by jojinshallar** [comment]
应该是SDK版本的问题，Bruno支持的Flutter SDK版本是2.2.2【参见：https://bruno.ke.com/page/guide/bruno】。

**Comment by xuejingpeng** [comment]
> 应该是SDK版本的问题，Brunosupport的Flutter SDK版本是2.2.2【参见：[https](https://bruno.ke.com/page/guide/bruno%E3%80%91%E3%80%82) ://bruno.ke.com/page/guide/bruno [】。](https://bruno.ke.com/page/guide/bruno%E3%80%91%E3%80%82)

想着什么时候可以更新一个版本

**Comment by biglin** [comment]
建议官方更新一下版本，遇到同样的问题，现在支持的版本有点低

**Comment by violinday** [comment]
> > 应该是SDK版本的问题，Brunosupport的Flutter SDK版本是2.2.2【参见：[https](https://bruno.ke.com/page/guide/bruno%E3%80%91%E3%80%82) ://bruno.ke.com/page/guide/bruno [】。](https://bruno.ke.com/page/guide/bruno%E3%80%91%E3%80%82)
> 
> 想着什么时候可以更新一个版本

@xuejingpeng @biglin 2.2.x 分支最新代码已修复这个问题，近期会发布小版本，感谢反馈~ ヾ(^▽^ヾ)

**Comment by suhli** [comment]
> > > 应该是SDK版本的问题，Brunosupport的Flutter SDK版本是2.2.2【参见：[https](https://bruno.ke.com/page/guide/bruno%E3%80%91%E3%80%82) ://bruno.ke.com/page/guide/bruno [】。](https://bruno.ke.com/page/guide/bruno%E3%80%91%E3%80%82)
> > 
> > 
> > 想着什么时候可以更新一个版本
> 
> @xuejingpeng @biglin 2.2.x 分支最新代码已修复这个问题，近期会发布小版本，感谢反馈~ ヾ(^▽^ヾ)

新版本发了吗?

**Comment by ccclly** [comment]
我也遇到了，flutter2.9

**Comment by violinday** [comment]
@xuejingpeng @ccclly  @suhli @biglin @jojinshallar 
近期发布了 2.1.0-nullsafty.1  PreRelease 版本，支持了空安全。
同时修复了该问题，经过初步测试，可在 2.10.0 版本正常运行。可尝试使用该版本验证功能。

Ps.  2.1.0-nullsafty.1 版本为非正式版本，由于适配了 null-safty， 且存在部分破坏性改动(breaking change)，可能引起代码编译错误。
详见：https://github.com/LianjiaTech/bruno/releases

**Comment by violinday** [comment]
Duplicate of #18, 关闭该 issue，可在#18 中讨论，感谢大家推动 Bruno 问题修复与优化~
