### ISSUE TITLE
BrnCommonActionSheet 点击后不能继续弹框问题

### ISSUE THREAD

**Issue by wuxaye** [LianjiaTech/bruno#520]
## 优化建议

BrnCommonActionSheet 的点击回调中，把  Navigator.of(context).pop([index, actions[index]]); 放到 clickCallBack 上面是不是比较好，不然的话在clickCallBack 继续弹框就会有问题，导致弹不出来。

`onTap: () {
            if (onItemClickInterceptor == null ||
                !onItemClickInterceptor!(index, actions[index])) {
              // 推荐使用回调方法处理点击事件!!!!!!!!!!
              if (clickCallBack != null) {
                clickCallBack!(index, actions[index]);
              }
              // 如果未拦截，则pop掉当前页面，并且携带信息（不建议使用此信息进行点击时间处理）
              Navigator.of(context).pop([index, actions[index]]);
            }
          }`

**Comment by zhoujuanjuan** [comment]
你好，我们之前考虑到这个问题，所以在点击关闭之前加了onItemClickInterceptor 回调的判断，如果你需要自己处理关闭逻辑请使用onItemClickInterceptor ，不需要使用clickCallBack

**Comment by wuxaye** [comment]
好的，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LianjiaTech/bruno"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月20日(星期二) 下午2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LianjiaTech/bruno] BrnCommonActionSheet 点击后不能继续弹框问题 (Issue #520)





 
你好，我们之前考虑到这个问题，所以在点击关闭之前加了onItemClickInterceptor 回调的判断，如果你需要自己处理关闭逻辑请使用onItemClickInterceptor ，不需要使用clickCallBack
