### ISSUE TITLE
[Feature]:  筛选支持横向滚动

### ISSUE THREAD

**Issue by shaunthegeek** [LianjiaTech/bruno#526]
## 功能需求

目前筛选列只能显示5列左右，数量稍微多一点，就无法显示：

![image](https://github.com/LianjiaTech/bruno/assets/4971414/21d234be-d331-4645-b386-7e4ac14a0dcd)

![image](https://github.com/LianjiaTech/bruno/assets/4971414/04cf85e2-2a75-4031-b78d-4b92c64eee31)

**1、运行环境**

* 运行设备
* 系统
* Bruno 版本 3.4.3
* Flutter Doctor 信息

**2、是否有与之关联的 issue**

**3、描述你期望的解决方案**

支持横向滚动，参考京东：

![image](https://github.com/LianjiaTech/bruno/assets/4971414/07ab8690-2070-4eb0-8fa7-5b716df9fad7)

**4、附加信息**

包括视频、图片等补充信息

**Comment by zhoujuanjuan** [comment]
你好，扩展性功能目前无法快速支持，需要的话建议fork工程参考实现，感谢使用
