### ISSUE TITLE
[Feature]:  选中后再点击则取消

### ISSUE THREAD

**Issue by shaunthegeek** [LianjiaTech/bruno#527]
## 功能需求

目前选项点一次选中，如果想取消，必须增加「不限」，而手机屏幕空间很宝贵。

内容需包含：

**1、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**2、是否有与之关联的 issue**

**3、描述你期望的解决方案**

建议增加：选中后再点击则取消

**4、附加信息**

参考：汽车之家

![截屏 2024-02-11 11 41 24](https://github.com/LianjiaTech/bruno/assets/4971414/15ada36a-7a87-460c-91e4-b5536f345421)

**Comment by zhoujuanjuan** [comment]
你好，扩展性功能目前无法快速支持，如果需要的话建议fork工程参考实现
