### ISSUE TITLE
 flutter3.22.0报错

### ISSUE THREAD

**Issue by linlamlinlam** [LianjiaTech/bruno#540]
Because bruno >=3.4.0 depends on intl ^0.18.0 and love depends on intl ^0.19.0, bruno >=3.4.0 is forbidden.
So, because love depends on bruno ^3.4.3, version solving failed.
exit code 1。
修改intl也运行不了Because love depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because love depends on intl ^0.18.0, version solving failed.

**Comment by violinday** [comment]
在项目选中强制依赖 intl 为 0.19.0  版本即可。

PS: 
目前flutter  3.22  还未适配，个别组件存在展示问题。可以等待使用适配后的新版本。
新版本适配目前逐步开始，完成时间待定。欢迎提交 pr ~
