### ISSUE TITLE
为什么demo在 IOS上的那么卡顿呢，我是iphone13pro max

### ISSUE THREAD

**Issue by hanwenbo** [LianjiaTech/bruno#58]
## 优化建议

标题格式：[Optimize]: 优化简介
每个页面的切换挺卡，首页的list滚动也是一顿一顿的

* 运行设备
iphone 13pro max
* 系统
ios最新
* Bruno 版本 
最新

**Comment by hanwenbo** [comment]
android   华为p30 感觉不到卡顿 
不过ios 我拿 iphone 13 、12 pro max 、iphonex 测试github的 readme.md 的二维码 app都很卡

**Comment by isslii** [comment]
没有适配flutter 2.8+版本

**Comment by violinday** [comment]
@isslii  Bruno 最新版本已经支持了 2.10.x ，可以看下发版记录： https://github.com/LianjiaTech/bruno/releases

**Comment by violinday** [comment]
hi @hanwenbo  
最新版本中已经对 Demo 做了初步优化，是否还存在卡顿问题？
