### ISSUE TITLE
demo安装不了

### ISSUE THREAD

**Issue by 986244073** [LianjiaTech/bruno#6]
安卓12 aosp 系统

**Comment by violinday** [comment]
@986244073  提供的信息太少，还请按照 #3  issue 提交规范补充下问题信息~  😀

ps: 可以通过 terminal 终端 运行 adb install demo.apk  查看具体安装失败原因

**Comment by violinday** [comment]
由于没有提供详细信息，展示关闭 issue，如果还有问题可以随时反馈~
