### ISSUE TITLE
BrnInputText 键盘会遮挡，在外层套SingleChildScrollView不起作用

### ISSUE THREAD

**Issue by xuejingpeng** [LianjiaTech/bruno#67]
## 问题提交

标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

问题的描述，请尽量使用简短、准确的语言

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by laiiihz** [comment]
可能是因为SingleChildScrollView的区域不够大 👀

**Comment by violinday** [comment]
抱歉，节前全力适配空安全，issue 跟进不及时。

如果可以的话，还请提供下可以复现问题的代码 😄

**Comment by violinday** [comment]
暂时关闭该 issue， 如果遇到问题可以重新提交或打开 issue，感谢反馈~
