### ISSUE TITLE
华为荣耀6X的Dialog中的输入框存在软键盘遮挡

### ISSUE THREAD

**Issue by jiangyubao** [LianjiaTech/bruno#7]
**BUG描述**
华为荣耀6X的Dialog中的输入框存在软键盘遮挡
**复现步骤**
安卓手机运行example，点击Dialog弹窗，点击”标题+信息+输入+按钮“，如下图：
![WechatIMG10](https://user-images.githubusercontent.com/1122460/145713508-30962e0e-2734-4ec7-973b-902d7fe85927.jpeg)

**运行环境**
设备：华为荣耀6X
系统：安卓版本8.0.0
Bruno 版本：1.22.4
Flutter Doctor 信息：

[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.63.0)
[✓] VS Code (version 1.63.0-insider)
[✓] Connected device (2 available)

**Comment by Nayuta403** [comment]
看起来是 BrnDialog 内部使用的 Column 实现的，其他好几个输入框也有这样的问题 @ShzMinato  ![image](https://user-images.githubusercontent.com/40540394/145720353-af7612bb-7fcc-48b3-8414-29a35b50721c.png)

**Comment by ShzMinato** [comment]
感谢🙏指正
@jiangyubao 问题已提交 #12
