### ISSUE TITLE
BrnPickerTitleConfig titleContent设置无效

### ISSUE THREAD

**Issue by GuanHuiLee** [LianjiaTech/bruno#70]
## 问题提交

BrnPickerTitleConfig titleContent 设置无效

需要在lib/src/components/picker/brn_bottom_picker.dart 第183行添加
      titleContent: widget.pickerTitleConfig.titleContent,

**Comment by hexintao** [comment]
多谢反馈问题～后续有兴趣也可以提 pr 进行修改😁
