### ISSUE TITLE
NoSuchMethodError: Class '_Timer' has no instance method 'onCancel'. 程序并没报错，控制台一直打印

### ISSUE THREAD

**Issue by junlandroid** [LianjiaTech/bruno#71]
## 问题提交

标题格式： NoSuchMethodError: Class '_Timer' has no instance method 'onCancel'. 程序并没报错，控制台一直打印

内容需包含：

**1、BUG 描述**

E/flutter (29819): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: Class '_Timer' has no instance method 'onCancel'.

E/flutter (29819): Receiver: Instance of '_Timer'

E/flutter (29819): Tried calling: onCancel()

E/flutter (29819): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)

E/flutter (29819): #1      _ActionSheetEntryPageState._showChangeableStyle.<anonymous closure>
package:example/…/actionsheet/actionsheet_entry_page.dart:391

E/flutter (29819): #2      _rootRunUnary (dart:async/zone.dart:1436:47)

E/flutter (29819): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)

E/flutter (29819): <asynchronous suspension>

E/flutter (29819):

E/flutter (29819): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: setState() called after dispose(): _StatefulBuilderState#60b89(lifecycle state: defunct, not mounted)

E/flutter (29819): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

E/flutter (29819): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.

E/flutter (29819): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (29819): #0      State.setState.<anonymous closure>
package:flutter/…/widgets/framework.dart:1052

E/flutter (29819): #1      State.setState
package:flutter/…/widgets/framework.dart:1087

E/flutter (29819): #2      _ActionSheetEntryPageState._showChangeableStyle.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:example/…/actionsheet/actionsheet_entry_page.dart:364

E/flutter (29819): #3      _rootRunUnary (dart:async/zone.dart:1436:47)

E/flutter (29819): #4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)

E/flutter (29819): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)

E/flutter (29819): #6      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)

E/flutter (29819): #7      _rootRunUnary (dart:async/zone.dart:1444:13)

E/flutter (29819): #8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)

E/flutter (29819): #9      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)

E/flutter (29819): #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)

E/flutter (29819): #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)

E/flutter (29819): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

E/flutter (29819):

I/chatty  (29819): uid=10146(com.beike.bruno) 1.ui identical 3 lines

**2、复现步骤**
ActionSheet > CommonActionSheet（通用样式ActionSheet，选择名动态变化）>  dismiss sheet 时 出现异常

**3、期望行为**

**4、运行环境**

* 运行设备 Pixel XL模拟器
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by leftcoding** [comment]
已修复
