### ISSUE TITLE
空安全版本什么时候差不多能用？

### ISSUE THREAD

**Issue by lyplay2** [LianjiaTech/bruno#85]
bruno组件非常牛，请问空安全版本什么时候能用？

**Comment by laiiihz** [comment]
可以看这个issue #49  以及 [projects](https://github.com/LianjiaTech/bruno/projects/1) 查看适配进度🤣

**Comment by sunyatas** [comment]
同问 好像延迟了呀

**Comment by ziyotko** [comment]
同问 好像延迟了呀

**Comment by zhoujuanjuan** [comment]
> 同问 好像延迟了呀

是的，延迟了，本周即将发布 unrelease 版本 ~

**Comment by violinday** [comment]
@lyplay2  @sunyatas  @ziyotko 
我们近期发布了空安全 prerelease 版本，可跟进 #27 ~
