### ISSUE TITLE
空安全适配

### ISSUE THREAD

**Issue by Sunyuwumengsheng** [LianjiaTech/bruno#9]
空安全适配什么时候上啊，

**Comment by zhoujuanjuan** [comment]
> 空安全适配什么时候上啊，

我们正在做空安全相关工作，由于体量较大，也期望可以让社区开发者参与其中，敬请期待

**Comment by hexintao** [comment]
最近我们发布了空安全的迁移指南[Null Safety Guide](https://github.com/LianjiaTech/bruno/wiki/Null-Safety-Guide)，空安全的事项比我们想象中的要多，如果有兴趣有时间，期待加入我们～

**Comment by violinday** [comment]
#49 空安全适配进展可在这里查看
