### ISSUE TITLE
datapicker 使用 BrnPickerConfig 设置的单一组件的确定颜色 设置无效

### ISSUE THREAD

**Issue by A-jiaotailang** [LianjiaTech/bruno#95]
版本2.0.0  

datapicker 使用 BrnPickerConfig 设置的单一组件的确定颜色 设置无效  设置 itemTextSelectedStyle 这个却可以

![image](https://user-images.githubusercontent.com/91598000/151287173-935bb4b9-e927-48d1-9d99-1e9161ec8601.png)

**Comment by violinday** [comment]
经过本地验证，themeData 配置黄色和粉色，在 iOS 14.4 模拟器上是生效的。可否提供详细的运行环境信息，我们继续排查下问题，感谢~

```
BrnMultiDataPicker(
  context: context,
  title: '来源',
  themeData: BrnPickerConfig(
    confirmTextStyle: BrnTextStyle(color: Colors.yellow),
    itemTextSelectedStyle: BrnTextStyle(color: Colors.pink),
  ),
  delegate: Brn1RowDelegate(firstSelectedIndex: 1),
  confirmClick: (list) {
    BrnToast.show(list.toString(), context);
  },
).show();
```

![image](https://user-images.githubusercontent.com/9434515/152742671-df3ab73a-240d-47d9-8198-ff196c73c1db.png)

**Comment by violinday** [comment]
暂时关闭该 issue，如果还有问题可以 提交或重新打开 issue，谢谢你对 Bruno 问题的反馈，让它边的更好~
