### ISSUE TITLE
可以参与到该项目开发吗？

### ISSUE THREAD

**Issue by huma8848888** [LianjiaTech/bruno#96]
## 优化建议

标题格式：[Optimize]: 优化简介

内容需包含：

**1、优化描述**

**2、关联组件**

**3、具体优化建议**

**4、运行环境（非必填）**

* 运行设备
* 系统
* Bruno 版本
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by violinday** [comment]
@huma8848888 
当然可以参与到项目开发~ 
Bruno 是一个开源共建的项目，非常欢迎大家参与进来，一起开发建设，让她越来越好~ ヽ(ﾟ∀ﾟ)ﾒ(ﾟ∀ﾟ)ﾉ 

目前 Bruno 刚开源，还有很多工作要做。有关 Bruno 部分后续计划，可以从 [projects](https://github.com/LianjiaTech/bruno/projects) 中了解。若对项目特别感兴趣，能长期参与项目开发维护，也可以申请加入项目维护组~

ps.抱歉哈，由于春节放假，没有及时回复。

**Comment by violinday** [comment]
欢迎一起参与共建😄，具体参见： #116

**Comment by huma8848888** [comment]
如何加入项目维护组？我的vx:A329887179,欢迎联系我 @violinday
